package ru.babin.autoproc.api.model;

public enum EModel {
	
	AC___ACE("Ace"),
	AC___ACECA("Aceca"),
	AC___COBRA("Cobra"),
	AC___DRUGAYA("Другая"),
	ACURA___CL("CL"),
	ACURA___CSX("CSX"),
	ACURA___EL("EL"),
	ACURA___INTEGRA("Integra"),
	ACURA___MDX("MDX"),
	ACURA___NSX("NSX"),
	ACURA___RDX("RDX"),
	ACURA___RL("RL"),
	ACURA___RSX("RSX"),
	ACURA___SLX("SLX"),
	ACURA___TL("TL"),
	ACURA___TLX("TLX"),
	ACURA___TSX("TSX"),
	ACURA___ZDX("ZDX"),
	ACURA___DRUGAYA("Другая"),
	ALFA_ROMEO___145("145"),
	ALFA_ROMEO___146("146"),
	ALFA_ROMEO___147("147"),
	ALFA_ROMEO___155("155"),
	ALFA_ROMEO___156("156"),
	ALFA_ROMEO___159("159"),
	ALFA_ROMEO___164("164"),
	ALFA_ROMEO___166("166"),
	ALFA_ROMEO___33("33"),
	ALFA_ROMEO___4C("4C"),
	ALFA_ROMEO___75("75"),
	ALFA_ROMEO___90("90"),
	ALFA_ROMEO___ARNA("Arna"),
	ALFA_ROMEO___BRERA("Brera"),
	ALFA_ROMEO___GIULIETTA("Giulietta"),
	ALFA_ROMEO___GT("GT"),
	ALFA_ROMEO___GTV("GTV"),
	ALFA_ROMEO___MITO("MiTo"),
	ALFA_ROMEO___RZ("RZ"),
	ALFA_ROMEO___SPIDER("Spider"),
	ALFA_ROMEO___SZ("SZ"),
	ALFA_ROMEO___DRUGAYA("Другая"),
	ALPINA___A1("A1"),
	ALPINA___A2("A2"),
	ALPINA___A4("A4"),
	ALPINA___B10("B10"),
	ALPINA___B11("B11"),
	ALPINA___B12("B12"),
	ALPINA___B3("B3"),
	ALPINA___B5("B5"),
	ALPINA___B6("B6"),
	ALPINA___B7("B7"),
	ALPINA___B8("B8"),
	ALPINA___B9("B9"),
	ALPINA___C1("C1"),
	ALPINA___C2("C2"),
	ALPINA___D10("D10"),
	ALPINA___D3("D3"),
	ALPINA___D5("D5"),
	ALPINA___XD3("XD3"),
	ALPINA___DRUGAYA("Другая"),
	ARO___10("10"),
	ARO___24("24"),
	ARO___SPARTANA("Spartana"),
	ARO___DRUGAYA("Другая"),
	ASIA___HI_TOPIC("Hi-topic"),
	ASIA___RETONA("Retona"),
	ASIA___ROCSTRA("Rocstra"),
	ASIA___DRUGAYA("Другая"),
	ASTON_MARTIN___CYGNET("Cygnet"),
	ASTON_MARTIN___DB7("DB7"),
	ASTON_MARTIN___DB9("DB9"),
	ASTON_MARTIN___DBS("DBS"),
	ASTON_MARTIN___LAGONDA("Lagonda"),
	ASTON_MARTIN___ONE_77("One-77"),
	ASTON_MARTIN___RAPIDE("Rapide"),
	ASTON_MARTIN___RAPIDE_S("Rapide S"),
	ASTON_MARTIN___V12_VANTAGE("V12 Vantage"),
	ASTON_MARTIN___V12_VANTAGE_S("V12 Vantage S"),
	ASTON_MARTIN___V8_VANTAGE("V8 Vantage"),
	ASTON_MARTIN___V8_VANTAGE_S("V8 Vantage S"),
	ASTON_MARTIN___VANQUISH("Vanquish"),
	ASTON_MARTIN___VIRAGE("Virage"),
	ASTON_MARTIN___DRUGAYA("Другая"),
	AUDI___100("100"),
	AUDI___200("200"),
	AUDI___80("80"),
	AUDI___90("90"),
	AUDI___A1("A1"),
	AUDI___A2("A2"),
	AUDI___A3("A3"),
	AUDI___A4("A4"),
	AUDI___A4_ALLROAD_QUATTRO("A4 Allroad Quattro"),
	AUDI___A5("A5"),
	AUDI___A6("A6"),
	AUDI___A6_ALLROAD_QUATTRO("A6 Allroad Quattro"),
	AUDI___A7("A7"),
	AUDI___A8("A8"),
	AUDI___ALLROAD("Allroad"),
	AUDI___CABRIOLET("Cabriolet"),
	AUDI___COUPE("Coupe"),
	AUDI___Q3("Q3"),
	AUDI___Q5("Q5"),
	AUDI___Q7("Q7"),
	AUDI___QUATTRO("Quattro"),
	AUDI___R8("R8"),
	AUDI___RS2("RS2"),
	AUDI___RS3("RS3"),
	AUDI___RS4("RS4"),
	AUDI___RS5("RS5"),
	AUDI___RS6("RS6"),
	AUDI___RS7("RS7"),
	AUDI___RS_Q3("RS Q3"),
	AUDI___S1("S1"),
	AUDI___S2("S2"),
	AUDI___S3("S3"),
	AUDI___S4("S4"),
	AUDI___S5("S5"),
	AUDI___S6("S6"),
	AUDI___S7("S7"),
	AUDI___S8("S8"),
	AUDI___SQ5("SQ5"),
	AUDI___TT("TT"),
	AUDI___TT_RS("TT RS"),
	AUDI___TTS("TTS"),
	AUDI___V8("V8"),
	AUDI___DRUGAYA("Другая"),
	BAW___FENIX("Fenix"),
	BAW___TONIK("Tonik"),
	BAW___DRUGAYA("Другая"),
	BENTLEY___ARNAGE("Arnage"),
	BENTLEY___AZURE("Azure"),
	BENTLEY___BROOKLANDS("Brooklands"),
	BENTLEY___CONTINENTAL("Continental"),
	BENTLEY___CONTINENTAL_FLYING_SPUR("Continental Flying Spur"),
	BENTLEY___CONTINENTAL_GT("Continental GT"),
	BENTLEY___CONTINENTAL_GTC("Continental GTC"),
	BENTLEY___CONTINENTAL_SUPERSPORTS("Continental Supersports"),
	BENTLEY___MULSANNE("Mulsanne"),
	BENTLEY___TURBO_R("Turbo R"),
	BENTLEY___DRUGAYA("Другая"),
	BMW___1M("1M"),
	BMW___1_SERIYA("1 серия"),
	BMW___2_SERIYA("2 серия"),
	BMW___3_SERIYA("3 серия"),
	BMW___3_SERIYA_GT("3 серия GT"),
	BMW___4_SERIYA("4 серия"),
	BMW___5_SERIYA("5 серия"),
	BMW___5_SERIYA_GT("5 серия GT"),
	BMW___6_SERIYA("6 серия"),
	BMW___7_SERIYA("7 серия"),
	BMW___8_SERIYA("8 серия"),
	BMW___I3("i3"),
	BMW___I8("i8"),
	BMW___M3("M3"),
	BMW___M4("M4"),
	BMW___M5("M5"),
	BMW___M6("M6"),
	BMW___X1("X1"),
	BMW___X3("X3"),
	BMW___X4("X4"),
	BMW___X5("X5"),
	BMW___X5_M("X5 M"),
	BMW___X6("X6"),
	BMW___X6_M("X6 M"),
	BMW___Z1("Z1"),
	BMW___Z3("Z3"),
	BMW___Z3_M("Z3 M"),
	BMW___Z4("Z4"),
	BMW___Z4_M("Z4 M"),
	BMW___Z8("Z8"),
	BMW___DRUGAYA("Другая"),
	BRILLIANCE___A1("A1"),
	BRILLIANCE___BS2("BS2"),
	BRILLIANCE___BS4("BS4"),
	BRILLIANCE___BS6("BS6"),
	BRILLIANCE___H530("H530"),
	BRILLIANCE___M1("M1"),
	BRILLIANCE___M2("M2"),
	BRILLIANCE___M3("M3"),
	BRILLIANCE___V5("V5"),
	BRILLIANCE___DRUGAYA("Другая"),
	BUFORI___LA_JOYA("La Joya"),
	BUFORI___DRUGAYA("Другая"),
	BUGATTI___EB("EB"),
	BUGATTI___GALIBIER("Galibier"),
	BUGATTI___VEYRON("Veyron"),
	BUGATTI___DRUGAYA("Другая"),
	BUICK___ALLURE("Allure"),
	BUICK___CENTURY("Century"),
	BUICK___ELECTRA("Electra"),
	BUICK___ENCLAVE("Enclave"),
	BUICK___EXCELLE("Excelle"),
	BUICK___GL8("GL8"),
	BUICK___HRV("HRV"),
	BUICK___LACROSSE("LaCrosse"),
	BUICK___LESABRE("LeSabre"),
	BUICK___LUCERNE("Lucerne"),
	BUICK___PARK_AVENUE("Park Avenue"),
	BUICK___RAINER("Rainer"),
	BUICK___REATTA("Reatta"),
	BUICK___REGAL("Regal"),
	BUICK___RENDEZVOUS("Rendezvous"),
	BUICK___RIVIERA("Riviera"),
	BUICK___ROADMASTER("Roadmaster"),
	BUICK___ROYAUM("Royaum"),
	BUICK___SEDAN("Sedan"),
	BUICK___SKYLARK("Skylark"),
	BUICK___TERRAZA("Terraza"),
	BUICK___DRUGAYA("Другая"),
	BYD___ET("ET"),
	BYD___F0("F0"),
	BYD___F2("F2"),
	BYD___F3("F3"),
	BYD___F6("F6"),
	BYD___FLYER("Flyer"),
	BYD___S8("S8"),
	BYD___DRUGAYA("Другая"),
	CADILLAC___ALLANTE("Allante"),
	CADILLAC___ATS("ATS"),
	CADILLAC___BLS("BLS"),
	CADILLAC___BROUGHAM("Brougham"),
	CADILLAC___CATERA("Catera"),
	CADILLAC___CTS("CTS"),
	CADILLAC___CTS_V("CTS-V"),
	CADILLAC___DE_VILLE("DE Ville"),
	CADILLAC___DTS("DTS"),
	CADILLAC___ELDORADO("Eldorado"),
	CADILLAC___ESCALADE("Escalade"),
	CADILLAC___FLEETWOOD("Fleetwood"),
	CADILLAC___LSE("LSE"),
	CADILLAC___SEVILLE("Seville"),
	CADILLAC___SRX("SRX"),
	CADILLAC___STS("STS"),
	CADILLAC___VICTORIA("Victoria"),
	CADILLAC___XLR("XLR"),
	CADILLAC___DRUGAYA("Другая"),
	CATERHAM___ACADEMY("Academy"),
	CATERHAM___CLASSIC("Classic"),
	CATERHAM___ROADSPORT("Roadsport"),
	CATERHAM___SUPERLIGHT("Superlight"),
	CATERHAM___DRUGAYA("Другая"),
	CHANGAN___CS35("CS35"),
	CHANGAN___EADO("Eado"),
	CHANGAN___RAETON("Raeton"),
	CHANGAN___SM_8("SM-8"),
	CHANGAN___Z_CHINE("Z-Chine"),
	CHANGAN___DRUGAYA("Другая"),
	CHANGFENG___FLYING_PICKUP("Flying PickUp"),
	CHANGFENG___FLYING_SUV("Flying SUV"),
	CHANGFENG___DRUGAYA("Другая"),
	CHERY___A3("A3"),
	CHERY___A5("A5"),
	CHERY___AMULET("Amulet"),
	CHERY___ARIZZO_3("Arizzo 3"),
	CHERY___ARIZZO_7("Arizzo 7"),
	CHERY___BONUS("Bonus"),
	CHERY___BONUS_3("Bonus 3"),
	CHERY___CROSSEASTAR("CrossEastar"),
	CHERY___FORA("Fora"),
	CHERY___INDIS("Indis"),
	CHERY___KIMO("Kimo"),
	CHERY___M11("M11"),
	CHERY___ORIENTAL_SON("Oriental Son"),
	CHERY___QQ("QQ"),
	CHERY___QQ6("QQ6"),
	CHERY___TIGGO("Tiggo"),
	CHERY___TIGGO_5("Tiggo 5"),
	CHERY___VERY("Very"),
	CHERY___DRUGAYA("Другая"),
	CHEVROLET___ALERO("Alero"),
	CHEVROLET___ASTRA("Astra"),
	CHEVROLET___ASTRO("Astro"),
	CHEVROLET___AVALANCHE("Avalanche"),
	CHEVROLET___AVEO("Aveo"),
	CHEVROLET___BEL_AIR("Bel Air"),
	CHEVROLET___BERETTA("Beretta"),
	CHEVROLET___BLAZER("Blazer"),
	CHEVROLET___C10("C10"),
	CHEVROLET___CAMARO("Camaro"),
	CHEVROLET___CAPRICE("Caprice"),
	CHEVROLET___CAPTIVA("Captiva"),
	CHEVROLET___CAVALIER("Cavalier"),
	CHEVROLET___CELEBRITY("Celebrity"),
	CHEVROLET___CELTA("Celta"),
	CHEVROLET___CHEVETTE("Chevette"),
	CHEVROLET___CLASSIC("Classic"),
	CHEVROLET___COBALT("Cobalt"),
	CHEVROLET___COLORADO("Colorado"),
	CHEVROLET___CORSA("Corsa"),
	CHEVROLET___CORSICA("Corsica"),
	CHEVROLET___CORVETTE("Corvette"),
	CHEVROLET___CRUZE("Cruze"),
	CHEVROLET___EPICA("Epica"),
	CHEVROLET___EQUINOX("Equinox"),
	CHEVROLET___EVANDA("Evanda"),
	CHEVROLET___EXPRESS("Express"),
	CHEVROLET___GEO_STORM("Geo Storm"),
	CHEVROLET___HHR("HHR"),
	CHEVROLET___IMPALA("Impala"),
	CHEVROLET___LACETTI("Lacetti"),
	CHEVROLET___LANOS("Lanos"),
	CHEVROLET___LUMINA("Lumina"),
	CHEVROLET___LUV_D_MAX("LUV D-MAX"),
	CHEVROLET___MALIBU("Malibu"),
	CHEVROLET___METRO("Metro"),
	CHEVROLET___MONTE_CARLO("Monte Carlo"),
	CHEVROLET___MONZA("Monza"),
	CHEVROLET___MW("MW"),
	CHEVROLET___NIVA("Niva"),
	CHEVROLET___NUBIRA("Nubira"),
	CHEVROLET___OMEGA("Omega"),
	CHEVROLET___ORLANDO("Orlando"),
	CHEVROLET___PRIZM("Prizm"),
	CHEVROLET___REZZO("Rezzo"),
	CHEVROLET___S10("S10"),
	CHEVROLET___SAIL("Sail"),
	CHEVROLET___SILVERADO("Silverado"),
	CHEVROLET___SONIC("Sonic"),
	CHEVROLET___SPARK("Spark"),
	CHEVROLET___SSR("SSR"),
	CHEVROLET___STARCRAFT("Starcraft"),
	CHEVROLET___SUBURBAN("Suburban"),
	CHEVROLET___TAHOE("Tahoe"),
	CHEVROLET___TAVERA("Tavera"),
	CHEVROLET___TRACKER("Tracker"),
	CHEVROLET___TRAILBLAZER("TrailBlazer"),
	CHEVROLET___TRANS_SPORT("Trans Sport"),
	CHEVROLET___TRAVERSE("Traverse"),
	CHEVROLET___UPLANDER("Uplander"),
	CHEVROLET___VAN("Van"),
	CHEVROLET___VECTRA("Vectra"),
	CHEVROLET___VENTURE("Venture"),
	CHEVROLET___VIVA("Viva"),
	CHEVROLET___VOLT("Volt"),
	CHEVROLET___ZAFIRA("Zafira"),
	CHEVROLET___DRUGAYA("Другая"),
	CHRYSLER___200("200"),
	CHRYSLER___300C("300C"),
	CHRYSLER___300M("300M"),
	CHRYSLER___ASPEN("Aspen"),
	CHRYSLER___CIRRUS("Cirrus"),
	CHRYSLER___CONCORDE("Concorde"),
	CHRYSLER___CROSSFIRE("Crossfire"),
	CHRYSLER___DAYTONA_SHELBY("Daytona Shelby"),
	CHRYSLER___DYNASTY("Dynasty"),
	CHRYSLER___FIFTH_AVENUE("Fifth Avenue"),
	CHRYSLER___GRAND_VOYAGER("Grand Voyager"),
	CHRYSLER___IMPERIAL("Imperial"),
	CHRYSLER___INTREPID("Intrepid"),
	CHRYSLER___LEBARON("LeBaron"),
	CHRYSLER___LHS("LHS"),
	CHRYSLER___NASSAU("Nassau"),
	CHRYSLER___NEON("Neon"),
	CHRYSLER___NEW_YORKER("New Yorker"),
	CHRYSLER___PACIFICA("Pacifica"),
	CHRYSLER___PROWLER("Prowler"),
	CHRYSLER___PT_CRUISER("PT Cruiser"),
	CHRYSLER___SARATOGA("Saratoga"),
	CHRYSLER___SEBRING("Sebring"),
	CHRYSLER___STRATUS("Stratus"),
	CHRYSLER___TOWN__COUNTRY("Town & Country"),
	CHRYSLER___VIPER("Viper"),
	CHRYSLER___VISION("Vision"),
	CHRYSLER___VOYAGER("Voyager"),
	CHRYSLER___DRUGAYA("Другая"),
	CITROEN___2_CV("2 CV"),
	CITROEN___ACADIANE("Acadiane"),
	CITROEN___AMI("Ami"),
	CITROEN___AX("AX"),
	CITROEN___BERLINGO("Berlingo"),
	CITROEN___BX("BX"),
	CITROEN___C1("C1"),
	CITROEN___C15("C15"),
	CITROEN___C2("C2"),
	CITROEN___C25("C25"),
	CITROEN___C3("C3"),
	CITROEN___C35("C35"),
	CITROEN___C3_PICASSO("C3 Picasso"),
	CITROEN___C4("C4"),
	CITROEN___C4_AIRCROSS("C4 Aircross"),
	CITROEN___C4_PICASSO("C4 Picasso"),
	CITROEN___C5("C5"),
	CITROEN___C6("C6"),
	CITROEN___C8("C8"),
	CITROEN___C_CROSSER("C-Crosser"),
	CITROEN___C_ELYSEE("C-Elysee"),
	CITROEN___CX("CX"),
	CITROEN___C_ZERO("C-Zero"),
	CITROEN___DS2("DS2"),
	CITROEN___DS3("DS3"),
	CITROEN___DS4("DS4"),
	CITROEN___DS5("DS5"),
	CITROEN___DS9("DS9"),
	CITROEN___DYANE("Dyane"),
	CITROEN___EVASION("Evasion"),
	CITROEN___EXPRESS("Express"),
	CITROEN___FAF("FAF"),
	CITROEN___GRAND_C4_PICASSO("Grand C4 Picasso"),
	CITROEN___GS("GS"),
	CITROEN___GSA("GSA"),
	CITROEN___JUMPER("Jumper"),
	CITROEN___JUMPY("Jumpy"),
	CITROEN___LN("LN"),
	CITROEN___LNA("LNA"),
	CITROEN___MEHARI("Mehari"),
	CITROEN___NEMO("Nemo"),
	CITROEN___SAXO("Saxo"),
	CITROEN___SYNERGIE("Synergie"),
	CITROEN___VISA("Visa"),
	CITROEN___XANTIA("Xantia"),
	CITROEN___XM("XM"),
	CITROEN___XSARA("Xsara"),
	CITROEN___XSARA_PICASSO("Xsara Picasso"),
	CITROEN___ZX("ZX"),
	CITROEN___DRUGAYA("Другая"),
	DACIA___1304("1304"),
	DACIA___1310("1310"),
	DACIA___1325("1325"),
	DACIA___1410("1410"),
	DACIA___DOKKER("Dokker"),
	DACIA___DUSTER("Duster"),
	DACIA___LODGY("Lodgy"),
	DACIA___LOGAN("Logan"),
	DACIA___NOVA("Nova"),
	DACIA___SANDERO("Sandero"),
	DACIA___DRUGAYA("Другая"),
	DADI___CITY_LEADING("City Leading"),
	DADI___SHUTTLE("Shuttle"),
	DADI___SMOOTHING("Smoothing"),
	DADI___DRUGAYA("Другая"),
	DAEWOO___ARCADIA("Arcadia"),
	DAEWOO___BROUGHAM("Brougham"),
	DAEWOO___CHARMAN("Charman"),
	DAEWOO___DAMAS("Damas"),
	DAEWOO___ESPERO("Espero"),
	DAEWOO___EVANDA("Evanda"),
	DAEWOO___G2X("G2X"),
	DAEWOO___GENTRA("Gentra"),
	DAEWOO___ISTANA("Istana"),
	DAEWOO___KALOS("Kalos"),
	DAEWOO___KORANDO("Korando"),
	DAEWOO___LABO("Labo"),
	DAEWOO___LACETTI("Lacetti"),
	DAEWOO___LANOS("Lanos"),
	DAEWOO___LEGANZA("Leganza"),
	DAEWOO___LEMANS("LeMans"),
	DAEWOO___MAGNUS("Magnus"),
	DAEWOO___MATIZ("Matiz"),
	DAEWOO___MUSSO("Musso"),
	DAEWOO___NEXIA("Nexia"),
	DAEWOO___NUBIRA("Nubira"),
	DAEWOO___PRINCE("Prince"),
	DAEWOO___RACER("Racer"),
	DAEWOO___REZZO("Rezzo"),
	DAEWOO___SENS("Sens"),
	DAEWOO___STATESMAN("Statesman"),
	DAEWOO___SUPER_SALON("Super Salon"),
	DAEWOO___TACUMA("Tacuma"),
	DAEWOO___TICO("Tico"),
	DAEWOO___TOSCA("Tosca"),
	DAEWOO___WINSTORM("Winstorm"),
	DAEWOO___DRUGAYA("Другая"),
	DAIHATSU___ALTIS("Altis"),
	DAIHATSU___APPLAUSE("Applause"),
	DAIHATSU___ATRAI("Atrai"),
	DAIHATSU___BE_GO("Be-go"),
	DAIHATSU___BOON("Boon"),
	DAIHATSU___CERIA("Ceria"),
	DAIHATSU___CHARADE("Charade"),
	DAIHATSU___CHARMANT("Charmant"),
	DAIHATSU___COO("Coo"),
	DAIHATSU___COPEN("Copen"),
	DAIHATSU___CUORE("Cuore"),
	DAIHATSU___DELTA("Delta"),
	DAIHATSU___ESSE("Esse"),
	DAIHATSU___FEROZA("Feroza"),
	DAIHATSU___HIJET("Hijet"),
	DAIHATSU___LEEZA("Leeza"),
	DAIHATSU___MATERIA("Materia"),
	DAIHATSU___MAX("MAX"),
	DAIHATSU___MIRA("Mira"),
	DAIHATSU___MOVE("Move"),
	DAIHATSU___NAKED("Naked"),
	DAIHATSU___OPTI("Opti"),
	DAIHATSU___PERODUA_VIVA("Perodua Viva"),
	DAIHATSU___PYZAR("Pyzar"),
	DAIHATSU___ROCKY("Rocky"),
	DAIHATSU___SIRION("Sirion"),
	DAIHATSU___SONICA("Sonica"),
	DAIHATSU___STORIA("Storia"),
	DAIHATSU___TAFT("Taft"),
	DAIHATSU___TANTO("Tanto"),
	DAIHATSU___TERIOS("Terios"),
	DAIHATSU___TREVIS("Trevis"),
	DAIHATSU___WILDCAT("Wildcat"),
	DAIHATSU___XENIA("Xenia"),
	DAIHATSU___YRV("YRV"),
	DAIHATSU___DRUGAYA("Другая"),
	DAIMLER___COUPE("Coupe"),
	DAIMLER___LANDAULETTE("Landaulette"),
	DAIMLER___LIMOUSINE("Limousine"),
	DAIMLER___SUPER_EIGHT("Super Eight"),
	DAIMLER___XJ("XJ"),
	DAIMLER___DRUGAYA("Другая"),
	DATSUN___MI_DO("mi-DO"),
	DATSUN___ON_DO("on-DO"),
	DATSUN___DRUGAYA("Другая"),
	DERWAYS___ANTELOPE("Antelope"),
	DERWAYS___AURORA("Aurora"),
	DERWAYS___COWBOY("Cowboy"),
	DERWAYS___LAND_CROWN("Land Crown"),
	DERWAYS___PLUTUS("Plutus"),
	DERWAYS___SALADIN("Saladin"),
	DERWAYS___SHUTTLE("Shuttle"),
	DERWAYS___DRUGAYA("Другая"),
	DODGE___AVENGER("Avenger"),
	DODGE___CALIBER("Caliber"),
	DODGE___CARAVAN("Caravan"),
	DODGE___CHALLENGER("Challenger"),
	DODGE___CHARGER("Charger"),
	DODGE___DAKOTA("Dakota"),
	DODGE___DAYTONA("Daytona"),
	DODGE___DURANGO("Durango"),
	DODGE___DYNASTY("Dynasty"),
	DODGE___GRAND_CARAVAN("Grand Caravan"),
	DODGE___INTREPID("Intrepid"),
	DODGE___JOURNEY("Journey"),
	DODGE___MAGNUM("Magnum"),
	DODGE___MONACO("Monaco"),
	DODGE___NEON("Neon"),
	DODGE___NITRO("Nitro"),
	DODGE___RAM("Ram"),
	DODGE___SHADOW("Shadow"),
	DODGE___SPIRIT("Spirit"),
	DODGE___STEALTH("Stealth"),
	DODGE___STRATUS("Stratus"),
	DODGE___VIPER("Viper"),
	DODGE___DRUGAYA("Другая"),
	DONG_FENG___EQ_1030("EQ 1030"),
	DONG_FENG___H30_CROSS("H30 Cross"),
	DONG_FENG___MPV("MPV"),
	DONG_FENG___OTING("Oting"),
	DONG_FENG___RICH("Rich"),
	DONG_FENG___S30("S30"),
	DONG_FENG___ZND("ZND"),
	DONG_FENG___DRUGAYA("Другая"),
	DONINVEST___ASSOL("Assol"),
	DONINVEST___KONDOR("Kondor"),
	DONINVEST___ORION("Orion"),
	DONINVEST___DRUGAYA("Другая"),
	EAGLE___PREMIER("Premier"),
	EAGLE___SS("SS"),
	EAGLE___SUMMIT("Summit"),
	EAGLE___TALON("Talon"),
	EAGLE___VISION("Vision"),
	EAGLE___DRUGAYA("Другая"),
	ECOMOTORS___ESTRIMA_BIRO("Estrima Biro"),
	ECOMOTORS___DRUGAYA("Другая"),
	FAW___ADMIRAL("Admiral"),
	FAW___BESTURN("Besturn"),
	FAW___BESTURN_B50("Besturn B50"),
	FAW___BESTURN_B70("Besturn B70"),
	FAW___BORA("Bora"),
	FAW___CITY_GOLF("City Golf"),
	FAW___JETTA("Jetta"),
	FAW___JINN("Jinn"),
	FAW___LANDMARK("Landmark"),
	FAW___V2("V2"),
	FAW___V5("V5"),
	FAW___VELA("Vela"),
	FAW___VITA("Vita"),
	FAW___VIZI("Vizi"),
	FAW___DRUGAYA("Другая"),
	FERRARI___208("208"),
	FERRARI___308("308"),
	FERRARI___328("328"),
	FERRARI___348("348"),
	FERRARI___355("355"),
	FERRARI___360_MODENA("360 Modena"),
	FERRARI___360_SPIDER("360 Spider"),
	FERRARI___412("412"),
	FERRARI___430("430"),
	FERRARI___456_GT("456 GT"),
	FERRARI___458_ITALIA("458 Italia"),
	FERRARI___458_SPIDER("458 Spider"),
	FERRARI___512("512"),
	FERRARI___550_BARCHETTA("550 Barchetta"),
	FERRARI___550_MARANELLO("550 Maranello"),
	FERRARI___575_MARANELLO("575 Maranello"),
	FERRARI___599_GTB_FIORANO("599 GTB Fiorano"),
	FERRARI___612_SCAGLIETTI("612 Scaglietti"),
	FERRARI___CALIFORNIA("California"),
	FERRARI___DINO("Dino"),
	FERRARI___ENZO("Enzo"),
	FERRARI___F12_BERLINETTA("F12 berlinetta"),
	FERRARI___F355("F355"),
	FERRARI___F40("F40"),
	FERRARI___F430("F430"),
	FERRARI___F430_SCUDERIA("F430 Scuderia"),
	FERRARI___F430_SPIDER("F430 Spider"),
	FERRARI___F50("F50"),
	FERRARI___FF("FF"),
	FERRARI___FXX("FXX"),
	FERRARI___MONDIAL("Mondial"),
	FERRARI___TESTAROSSA("Testarossa"),
	FERRARI___DRUGAYA("Другая"),
	FIAT___124("124"),
	FIAT___126("126"),
	FIAT___127("127"),
	FIAT___131("131"),
	FIAT___500("500"),
	FIAT___600("600"),
	FIAT___ALBEA("Albea"),
	FIAT___BARCHETTA("Barchetta"),
	FIAT___BRAVA("Brava"),
	FIAT___BRAVO("Bravo"),
	FIAT___CINQUECENTO("Cinquecento"),
	FIAT___COUPE("Coupe"),
	FIAT___CROMA("Croma"),
	FIAT___DOBLO("Doblo"),
	FIAT___DUCATO("Ducato"),
	FIAT___DUNA("Duna"),
	FIAT___FIORINO("Fiorino"),
	FIAT___FREEMONT("Freemont"),
	FIAT___IDEA("Idea"),
	FIAT___LINEA("Linea"),
	FIAT___MAREA("Marea"),
	FIAT___MULTIPLA("Multipla"),
	FIAT___NEW_500("New 500"),
	FIAT___PALIO("Palio"),
	FIAT___PANDA("Panda"),
	FIAT___PUNTO("Punto"),
	FIAT___REGATA("Regata"),
	FIAT___RITMO("Ritmo"),
	FIAT___SCUDO("Scudo"),
	FIAT___SEDICI("Sedici"),
	FIAT___SEICENTO("Seicento"),
	FIAT___SIENA("Siena"),
	FIAT___STILO("Stilo"),
	FIAT___STRADA("Strada"),
	FIAT___TEMPRA("Tempra"),
	FIAT___TIPO("Tipo"),
	FIAT___ULYSSE("Ulysse"),
	FIAT___UNO("Uno"),
	FIAT___X19("X1/9"),
	FIAT___DRUGAYA("Другая"),
	FORD___AEROSTAR("Aerostar"),
	FORD___ASPIRE("Aspire"),
	FORD___BRONCO("Bronco"),
	FORD___CAPRI("Capri"),
	FORD___C_MAX("C-MAX"),
	FORD___CONSUL("Consul"),
	FORD___CONTOUR("Contour"),
	FORD___COUGAR("Cougar"),
	FORD___COURIER("Courier"),
	FORD___CROWN_VICTORIA("Crown Victoria"),
	FORD___ECONOLINE("Econoline"),
	FORD___ECONOVAN("Econovan"),
	FORD___ECOSPORT("EcoSport"),
	FORD___EDGE("Edge"),
	FORD___ESCAPE("Escape"),
	FORD___ESCORT("Escort"),
	FORD___EVEREST("Everest"),
	FORD___EXCURSION("Excursion"),
	FORD___EXPEDITION("Expedition"),
	FORD___EXPLORER("Explorer"),
	FORD___F_150("F-150"),
	FORD___F_250("F-250"),
	FORD___F_350("F-350"),
	FORD___FESTIVA("Festiva"),
	FORD___FIESTA("Fiesta"),
	FORD___FIESTA_ST("Fiesta ST"),
	FORD___FIVE_HUNDRED("Five Hundred"),
	FORD___FLEX("Flex"),
	FORD___FOCUS("Focus"),
	FORD___FOCUS_RS("Focus RS"),
	FORD___FOCUS_ST("Focus ST"),
	FORD___FREESTAR("Freestar"),
	FORD___FREESTYLE("Freestyle"),
	FORD___FUSION("Fusion"),
	FORD___GALAXY("Galaxy"),
	FORD___GRANADA("Granada"),
	FORD___GRAND_C_MAX("Grand C-MAX"),
	FORD___GT("GT"),
	FORD___KA("Ka"),
	FORD___KUGA("Kuga"),
	FORD___LASER("Laser"),
	FORD___MAVERICK("Maverick"),
	FORD___MONDEO("Mondeo"),
	FORD___MONDEO_ST("Mondeo ST"),
	FORD___MUSTANG("Mustang"),
	FORD___ORION("Orion"),
	FORD___PROBE("Probe"),
	FORD___PUMA("Puma"),
	FORD___RANGER("Ranger"),
	FORD___SCORPIO("Scorpio"),
	FORD___SHELBY("Shelby"),
	FORD___SIERRA("Sierra"),
	FORD___S_MAX("S-MAX"),
	FORD___TAUNUS("Taunus"),
	FORD___TAURUS("Taurus"),
	FORD___TEMPO("Tempo"),
	FORD___THUNDERBIRD("Thunderbird"),
	FORD___TOURNEO("Tourneo"),
	FORD___TOURNEO_CONNECT("Tourneo Connect"),
	FORD___TOURNEO_CUSTOM("Tourneo Custom"),
	FORD___TRANSIT("Transit"),
	FORD___WINDSTAR("Windstar"),
	FORD___DRUGAYA("Другая"),
	GEELY___CK("CK"),
	GEELY___EMGRAND("Emgrand"),
	GEELY___EMGRAND_X7("Emgrand X7"),
	GEELY___GC6("GC6"),
	GEELY___MERRIE("Merrie"),
	GEELY___MK("MK"),
	GEELY___MK_CROSS("MK Cross"),
	GEELY___OTAKA("Otaka"),
	GEELY___VISION("Vision"),
	GEELY___DRUGAYA("Другая"),
	GEO___METRO("Metro"),
	GEO___PRIZM("Prizm"),
	GEO___SPECTRUM("Spectrum"),
	GEO___STORM("Storm"),
	GEO___TRACKER("Tracker"),
	GEO___DRUGAYA("Другая"),
	GMC___ACADIA("Acadia"),
	GMC___AVENTRA("Aventra"),
	GMC___BERLINA("Berlina"),
	GMC___CALAIS("Calais"),
	GMC___CANYON("Canyon"),
	GMC___CAPRICE("Caprice"),
	GMC___COMMODORE("Commodore"),
	GMC___CRUZE("Cruze"),
	GMC___ENVOY("Envoy"),
	GMC___JIMMY("Jimmy"),
	GMC___SAFARI("Safari"),
	GMC___SAVANA("Savana"),
	GMC___SIERRA("Sierra"),
	GMC___STATESMAN("Statesman"),
	GMC___SUBURBAN("Suburban"),
	GMC___TYPHOON("Typhoon"),
	GMC___VANDURA("Vandura"),
	GMC___YUKON("Yukon"),
	GMC___DRUGAYA("Другая"),
	GREAT_WALL___COOLBEAR("Coolbear"),
	GREAT_WALL___COWRY("Cowry"),
	GREAT_WALL___DEER("Deer"),
	GREAT_WALL___FLORID("Florid"),
	GREAT_WALL___HOVER("Hover"),
	GREAT_WALL___PEGASUS("Pegasus"),
	GREAT_WALL___PERI("Peri"),
	GREAT_WALL___SAFE("Safe"),
	GREAT_WALL___SAILOR("Sailor"),
	GREAT_WALL___SOKOL("Sokol"),
	GREAT_WALL___WINGLE("Wingle"),
	GREAT_WALL___DRUGAYA("Другая"),
	HAFEI___BRIO("Brio"),
	HAFEI___PRINCIP("Princip"),
	HAFEI___SAIBAO("Saibao"),
	HAFEI___SIGMA("Sigma"),
	HAFEI___SIMBO("Simbo"),
	HAFEI___DRUGAYA("Другая"),
	HAIMA___2("2"),
	HAIMA___3("3"),
	HAIMA___7("7"),
	HAIMA___DRUGAYA("Другая"),
	HAVAL___H1("H1"),
	HAVAL___H2("H2"),
	HAVAL___H6("H6"),
	HAVAL___H7("H7"),
	HAVAL___H8("H8"),
	HAVAL___H9("H9"),
	HAVAL___DRUGAYA("Другая"),
	HAWTAI___BOLIGER("Boliger"),
	HAWTAI___DRUGAYA("Другая"),
	HONDA___ACCORD("Accord"),
	HONDA___AIRWAVE("Airwave"),
	HONDA___ASCOT("Ascot"),
	HONDA___AVANCIER("Avancier"),
	HONDA___BEAT("Beat"),
	HONDA___CAPA("Capa"),
	HONDA___CITY("City"),
	HONDA___CIVIC("Civic"),
	HONDA___CONCERTO("Concerto"),
	HONDA___CROSSROAD("Crossroad"),
	HONDA___CROSSTOUR("Crosstour"),
	HONDA___CR_V("CR-V"),
	HONDA___CR_X("CR-X"),
	HONDA___CR_Z("CR-Z"),
	HONDA___DOMANI("Domani"),
	HONDA___EDIX("Edix"),
	HONDA___ELEMENT("Element"),
	HONDA___ELYSION("Elysion"),
	HONDA___FIT("Fit"),
	HONDA___FIT_ARIA("Fit Aria"),
	HONDA___FR_V("FR-V"),
	HONDA___HR_V("HR-V"),
	HONDA___INSIGHT("Insight"),
	HONDA___INSPIRE("Inspire"),
	HONDA___INTEGRA("Integra"),
	HONDA___JAZZ("Jazz"),
	HONDA___LAGREAT("Lagreat"),
	HONDA___LEGEND("Legend"),
	HONDA___LIFE("Life"),
	HONDA___LOGO("Logo"),
	HONDA___MDX("MDX"),
	HONDA___MOBILIO("Mobilio"),
	HONDA___NSX("NSX"),
	HONDA___ODYSSEY("Odyssey"),
	HONDA___ORTHIA("Orthia"),
	HONDA___PARTNER("Partner"),
	HONDA___PASSPORT("Passport"),
	HONDA___PILOT("Pilot"),
	HONDA___PRELUDE("Prelude"),
	HONDA___QUINTET("Quintet"),
	HONDA___RAFAGA("Rafaga"),
	HONDA___RIDGELINE("Ridgeline"),
	HONDA___S2000("S2000"),
	HONDA___SABER("Saber"),
	HONDA___SHUTTLE("Shuttle"),
	HONDA___SM_X("SM-X"),
	HONDA___STEPWGN("Stepwgn"),
	HONDA___STREAM("Stream"),
	HONDA___THAT_S("That S"),
	HONDA___TODAY("Today"),
	HONDA___TORNEO("Torneo"),
	HONDA___VAMOS("Vamos"),
	HONDA___VIGOR("Vigor"),
	HONDA___Z("Z"),
	HONDA___ZEST("Zest"),
	HONDA___DRUGAYA("Другая"),
	HUANGHAI___ANTELOPE("Antelope"),
	HUANGHAI___LANDSCAPE("Landscape"),
	HUANGHAI___MAJOR("Major"),
	HUANGHAI___PLUTUS("Plutus"),
	HUANGHAI___DRUGAYA("Другая"),
	HUMMER___H1("H1"),
	HUMMER___H2("H2"),
	HUMMER___H3("H3"),
	HUMMER___DRUGAYA("Другая"),
	HURTAN___ALBAYCIN("Albaycin"),
	HURTAN___GRAND_ALBAYCIN("Grand Albaycin"),
	HURTAN___DRUGAYA("Другая"),
	HYUNDAI___ACCENT("Accent"),
	HYUNDAI___ATOS("Atos"),
	HYUNDAI___AVANTE("Avante"),
	HYUNDAI___CENTENNIAL("Centennial"),
	HYUNDAI___COUPE("Coupe"),
	HYUNDAI___DYNASTY("Dynasty"),
	HYUNDAI___ELANTRA("Elantra"),
	HYUNDAI___EQUUS("Equus"),
	HYUNDAI___EXCEL("Excel"),
	HYUNDAI___GALLOPER("Galloper"),
	HYUNDAI___GENESIS("Genesis"),
	HYUNDAI___GETZ("Getz"),
	HYUNDAI___GRANDEUR("Grandeur"),
	HYUNDAI___H_1_GRAND_STAREX("H-1 (Grand Starex)"),
	HYUNDAI___I10("i10"),
	HYUNDAI___I20("i20"),
	HYUNDAI___I30("i30"),
	HYUNDAI___I40("i40"),
	HYUNDAI___IX20("ix20"),
	HYUNDAI___IX35("ix35"),
	HYUNDAI___IX55("ix55"),
	HYUNDAI___LANTRA("Lantra"),
	HYUNDAI___LAVITA("Lavita"),
	HYUNDAI___MARCIA("Marcia"),
	HYUNDAI___MATRIX("Matrix"),
	HYUNDAI___NF("NF"),
	HYUNDAI___PONY("Pony"),
	HYUNDAI___PORTER("Porter"),
	HYUNDAI___SANTA_FE("Santa Fe"),
	HYUNDAI___SANTAMO("Santamo"),
	HYUNDAI___S_COUPE("S-Coupe"),
	HYUNDAI___SOLARIS("Solaris"),
	HYUNDAI___SONATA("Sonata"),
	HYUNDAI___STAREX("Starex"),
	HYUNDAI___STELLAR("Stellar"),
	HYUNDAI___TERRACAN("Terracan"),
	HYUNDAI___TIBURON("Tiburon"),
	HYUNDAI___TRAJET("Trajet"),
	HYUNDAI___TUCSON("Tucson"),
	HYUNDAI___TUSCANI("Tuscani"),
	HYUNDAI___VELOSTER("Veloster"),
	HYUNDAI___VERACRUZ("Veracruz"),
	HYUNDAI___VERNA("Verna"),
	HYUNDAI___XG("XG"),
	HYUNDAI___DRUGAYA("Другая"),
	INFINITI___EX25("EX25"),
	INFINITI___EX35("EX35"),
	INFINITI___EX37("EX37"),
	INFINITI___FX30("FX30"),
	INFINITI___FX35("FX35"),
	INFINITI___FX37("FX37"),
	INFINITI___FX45("FX45"),
	INFINITI___FX50("FX50"),
	INFINITI___FX56("FX56"),
	INFINITI___G20("G20"),
	INFINITI___G25("G25"),
	INFINITI___G35("G35"),
	INFINITI___G37("G37"),
	INFINITI___I30("I30"),
	INFINITI___I35("I35"),
	INFINITI___J30("J30"),
	INFINITI___JX("JX"),
	INFINITI___M25("M25"),
	INFINITI___M30("M30"),
	INFINITI___M35("M35"),
	INFINITI___M37("M37"),
	INFINITI___M45("M45"),
	INFINITI___M56("M56"),
	INFINITI___Q45("Q45"),
	INFINITI___Q50("Q50"),
	INFINITI___Q60("Q60"),
	INFINITI___Q70("Q70"),
	INFINITI___QX4("QX4"),
	INFINITI___QX50("QX50"),
	INFINITI___QX56("QX56"),
	INFINITI___QX60("QX60"),
	INFINITI___QX70("QX70"),
	INFINITI___QX80("QX80"),
	INFINITI___DRUGAYA("Другая"),
	IRAN_KHODRO___PARS("Pars"),
	IRAN_KHODRO___SAMAND("Samand"),
	IRAN_KHODRO___SOREN("Soren"),
	IRAN_KHODRO___DRUGAYA("Другая"),
	ISUZU___AMIGO("Amigo"),
	ISUZU___ASCENDER("Ascender"),
	ISUZU___ASKA("Aska"),
	ISUZU___AXIOM("Axiom"),
	ISUZU___BIGHORN("Bighorn"),
	ISUZU___CAMPO("Campo"),
	ISUZU___D_MAX("D-Max"),
	ISUZU___FASTER("Faster"),
	ISUZU___FILLY("Filly"),
	ISUZU___GEMINI("Gemini"),
	ISUZU___I_MARK("I-Mark"),
	ISUZU___IMPULSE("Impulse"),
	ISUZU___MU("MU"),
	ISUZU___PIAZZA("Piazza"),
	ISUZU___RODEO("Rodeo"),
	ISUZU___TROOPER("Trooper"),
	ISUZU___VEHICROSS("VehiCross"),
	ISUZU___WIZARD("Wizard"),
	ISUZU___DRUGAYA("Другая"),
	IVECO___DAILY("Daily"),
	IVECO___DRUGAYA("Другая"),
	JAC___J2("J2"),
	JAC___J5("J5"),
	JAC___REFINE("Refine"),
	JAC___REIN("Rein"),
	JAC___S5("S5"),
	JAC___DRUGAYA("Другая"),
	JAGUAR___E_TYPE("E-type"),
	JAGUAR___F_TYPE("F-type"),
	JAGUAR___S_TYPE("S-type"),
	JAGUAR___XF("XF"),
	JAGUAR___XFR("XFR"),
	JAGUAR___XJ("XJ"),
	JAGUAR___XJ220("XJ220"),
	JAGUAR___XJR("XJR"),
	JAGUAR___XJS("XJS"),
	JAGUAR___XK("XK"),
	JAGUAR___XKR("XKR"),
	JAGUAR___XKR_S("XKR-S"),
	JAGUAR___X_TYPE("X-type"),
	JAGUAR___DRUGAYA("Другая"),
	JEEP___CHEROKEE("Cherokee"),
	JEEP___COMMANDER("Commander"),
	JEEP___COMPASS("Compass"),
	JEEP___GRAND_CHEROKEE("Grand Cherokee"),
	JEEP___LIBERTY("Liberty"),
	JEEP___PATRIOT("Patriot"),
	JEEP___WRANGLER("Wrangler"),
	JEEP___DRUGAYA("Другая"),
	JINBEI___HAISE("Haise"),
	JINBEI___DRUGAYA("Другая"),
	JMC___BAODIAN("Baodian"),
	JMC___DRUGAYA("Другая"),
	KIA___AVELLA("Avella"),
	KIA___BESTA("Besta"),
	KIA___CADENZA("Cadenza"),
	KIA___CAPITAL("Capital"),
	KIA___CARENS("Carens"),
	KIA___CARNIVAL("Carnival"),
	KIA___CEED("cee'd"),
	KIA___CEED_GT("cee`d GT"),
	KIA___CERATO("Cerato"),
	KIA___CLARUS("Clarus"),
	KIA___CONCORD("Concord"),
	KIA___ENTERPRISE("Enterprise"),
	KIA___JOICE("Joice"),
	KIA___K("K"),
	KIA___MAGENTIS("Magentis"),
	KIA___MOHAVE("Mohave"),
	KIA___OPIRUS("Opirus"),
	KIA___OPTIMA("Optima"),
	KIA___PICANTO("Picanto"),
	KIA___POTENTIA("Potentia"),
	KIA___PREGIO("Pregio"),
	KIA___PRIDE("Pride"),
	KIA___QUORIS("Quoris"),
	KIA___RAY("Ray"),
	KIA___RETONA("Retona"),
	KIA___RIO("Rio"),
	KIA___SEDONA("Sedona"),
	KIA___SEPHIA("Sephia"),
	KIA___SHUMA("Shuma"),
	KIA___SORENTO("Sorento"),
	KIA___SOUL("Soul"),
	KIA___SPECTRA("Spectra"),
	KIA___SPORTAGE("Sportage"),
	KIA___VENGA("Venga"),
	KIA___VISTO("Visto"),
	KIA___X_TREK("X-Trek"),
	KIA___DRUGAYA("Другая"),
	LAMBORGHINI___AVENTADOR("Aventador"),
	LAMBORGHINI___COUNTACH("Countach"),
	LAMBORGHINI___DIABLO("Diablo"),
	LAMBORGHINI___ESPADA("Espada"),
	LAMBORGHINI___GALLARDO("Gallardo"),
	LAMBORGHINI___JALPA("Jalpa"),
	LAMBORGHINI___LM002("LM002"),
	LAMBORGHINI___MURCIELAGO("Murcielago"),
	LAMBORGHINI___REVENTON("Reventon"),
	LAMBORGHINI___DRUGAYA("Другая"),
	LANCIA___DEDRA("Dedra"),
	LANCIA___DELTA("Delta"),
	LANCIA___FULVIA("Fulvia"),
	LANCIA___KAPPA("Kappa"),
	LANCIA___LYBRA("Lybra"),
	LANCIA___MUSA("Musa"),
	LANCIA___PHEDRA("Phedra"),
	LANCIA___PRISMA("Prisma"),
	LANCIA___THEMA("Thema"),
	LANCIA___THESIS("Thesis"),
	LANCIA___TREVI("Trevi"),
	LANCIA___YPSILON("Ypsilon"),
	LANCIA___ZETA("Zeta"),
	LANCIA___DRUGAYA("Другая"),
	LAND_ROVER___DEFENDER("Defender"),
	LAND_ROVER___DISCOVERY("Discovery"),
	LAND_ROVER___FREELANDER("Freelander"),
	LAND_ROVER___RANGE_ROVER("Range Rover"),
	LAND_ROVER___RANGE_ROVER_EVOQUE("Range Rover Evoque"),
	LAND_ROVER___RANGE_ROVER_SPORT("Range Rover Sport"),
	LAND_ROVER___SERIES_I("Series I"),
	LAND_ROVER___DRUGAYA("Другая"),
	LANDWIND___SUV("SUV"),
	LANDWIND___X6("X6"),
	LANDWIND___DRUGAYA("Другая"),
	LDV___MAXUS("Maxus"),
	LDV___DRUGAYA("Другая"),
	LEXUS___CT("CT"),
	LEXUS___ES("ES"),
	LEXUS___GS("GS"),
	LEXUS___GX("GX"),
	LEXUS___HS("HS"),
	LEXUS___IS("IS"),
	LEXUS___IS_F("IS F"),
	LEXUS___LFA("LFA"),
	LEXUS___LS("LS"),
	LEXUS___LX("LX"),
	LEXUS___NX("NX"),
	LEXUS___RX("RX"),
	LEXUS___SC("SC"),
	LEXUS___DRUGAYA("Другая"),
	LIFAN___BREEZ("Breez"),
	LIFAN___CEBRIUM("Cebrium"),
	LIFAN___CELLIYA("Celliya"),
	LIFAN___SMILY("Smily"),
	LIFAN___SOLANO("Solano"),
	LIFAN___X60("X60"),
	LIFAN___DRUGAYA("Другая"),
	LINCOLN___AVIATOR("Aviator"),
	LINCOLN___BLACKWOOD("Blackwood"),
	LINCOLN___CONTINENTAL("Continental"),
	LINCOLN___LS("LS"),
	LINCOLN___MARK("Mark"),
	LINCOLN___MARK_LT("Mark LT"),
	LINCOLN___MKX("MKX"),
	LINCOLN___MKZ("MKZ"),
	LINCOLN___NAVIGATOR("Navigator"),
	LINCOLN___TOWN_CAR("Town Car"),
	LINCOLN___ZEPHYR("Zephyr"),
	LINCOLN___DRUGAYA("Другая"),
	LOTUS___ECLAT("Eclat"),
	LOTUS___ELAN("Elan"),
	LOTUS___ELISE("Elise"),
	LOTUS___ELISE_S("Elise S"),
	LOTUS___ELITE("Elite"),
	LOTUS___ESPRIT("Esprit"),
	LOTUS___EUROPA("Europa"),
	LOTUS___EVORA("Evora"),
	LOTUS___EVORA_S("Evora S"),
	LOTUS___EXCEL("Excel"),
	LOTUS___EXIGE("Exige"),
	LOTUS___EXIGE_S("Exige S"),
	LOTUS___DRUGAYA("Другая"),
	LUXGEN___5_SEDAN("5 Sedan"),
	LUXGEN___7_MPV("7 MPV"),
	LUXGEN___7_SUV("7 SUV"),
	LUXGEN___DRUGAYA("Другая"),
	MAHINDRA___ARMADA("Armada"),
	MAHINDRA___CJ("CJ"),
	MAHINDRA___COMMANDER("Commander"),
	MAHINDRA___MARSHAL("Marshal"),
	MAHINDRA___DRUGAYA("Другая"),
	MARUSSIA___B1("B1"),
	MARUSSIA___B2("B2"),
	MARUSSIA___DRUGAYA("Другая"),
	MASERATI___228("228"),
	MASERATI___3200_GT("3200 GT"),
	MASERATI___4300_GT_COUPE("4300 GT Coupe"),
	MASERATI___BARCHETTA_STRADALE("Barchetta Stradale"),
	MASERATI___BITURBO("Biturbo"),
	MASERATI___BORA("Bora"),
	MASERATI___CHUBASCO("Chubasco"),
	MASERATI___COUPE("Coupe"),
	MASERATI___GHIBLI("Ghibli"),
	MASERATI___GRANCABRIO("GranCabrio"),
	MASERATI___GRANSPORT("GranSport"),
	MASERATI___GRANTURISMO("GranTurismo"),
	MASERATI___INDY("Indy"),
	MASERATI___KARIF("Karif"),
	MASERATI___KHAMSIN("Khamsin"),
	MASERATI___KYALAMI("Kyalami"),
	MASERATI___MC12("MC12"),
	MASERATI___MERAK("Merak"),
	MASERATI___MEXICO("Mexico"),
	MASERATI___QUATTROPORTE("Quattroporte"),
	MASERATI___ROYALE("Royale"),
	MASERATI___SHAMAL("Shamal"),
	MASERATI___SPYDER("Spyder"),
	MASERATI___DRUGAYA("Другая"),
	MAYBACH___57("57"),
	MAYBACH___57S("57S"),
	MAYBACH___62("62"),
	MAYBACH___62S("62S"),
	MAYBACH___DRUGAYA("Другая"),
	MAZDA___1000("1000"),
	MAZDA___121("121"),
	MAZDA___1300("1300"),
	MAZDA___2("2"),
	MAZDA___3("3"),
	MAZDA___323("323"),
	MAZDA___3_MPS("3 MPS"),
	MAZDA___5("5"),
	MAZDA___6("6"),
	MAZDA___616("616"),
	MAZDA___626("626"),
	MAZDA___6_MPS("6 MPS"),
	MAZDA___818("818"),
	MAZDA___929("929"),
	MAZDA___ATENZA("Atenza"),
	MAZDA___AXELA("Axela"),
	MAZDA___AZ_WAGON("AZ-Wagon"),
	MAZDA___BIANTE("Biante"),
	MAZDA___BONGO("Bongo"),
	MAZDA___B_SERIES("B-Series"),
	MAZDA___BT_50("BT-50"),
	MAZDA___CAPELLA("Capella"),
	MAZDA___CAROL("Carol"),
	MAZDA___CLEF("Clef"),
	MAZDA___CRONOS("Cronos"),
	MAZDA___CX_5("CX-5"),
	MAZDA___CX_7("CX-7"),
	MAZDA___CX_9("CX-9"),
	MAZDA___DEMIO("Demio"),
	MAZDA___EFINI("Efini"),
	MAZDA___EUNOS("Eunos"),
	MAZDA___EUNOS_COSMO("Eunos Cosmo"),
	MAZDA___FAMILIA("Familia"),
	MAZDA___LANTIS("Lantis"),
	MAZDA___LAPUTA("Laputa"),
	MAZDA___LEVANTE("Levante"),
	MAZDA___LUCE("Luce"),
	MAZDA___MILLENIA("Millenia"),
	MAZDA___MPV("MPV"),
	MAZDA___MX_3("MX-3"),
	MAZDA___MX_5("MX-5"),
	MAZDA___MX_6("MX-6"),
	MAZDA___NAVAJO("Navajo"),
	MAZDA___PREMACY("Premacy"),
	MAZDA___PROCEED("Proceed"),
	MAZDA___PROTEGE("Protege"),
	MAZDA___REVUE("Revue"),
	MAZDA___ROADSTER("Roadster"),
	MAZDA___RUSTLER("Rustler"),
	MAZDA___RX_7("RX-7"),
	MAZDA___RX_8("RX-8"),
	MAZDA___SCRUM("Scrum"),
	MAZDA___SENTIA("Sentia"),
	MAZDA___SPIANO("Spiano"),
	MAZDA___TRIBUTE("Tribute"),
	MAZDA___VANTREND("Vantrend"),
	MAZDA___VERISA("Verisa"),
	MAZDA___XEDOS_6("Xedos 6"),
	MAZDA___XEDOS_9("Xedos 9"),
	MAZDA___DRUGAYA("Другая"),
	MERCEDES_BENZ___190_W201("190 (W201)"),
	MERCEDES_BENZ___AMG_GT("AMG GT"),
	MERCEDES_BENZ___A_KLASS("A-класс"),
	MERCEDES_BENZ___A_KLASS_AMG("A-класс AMG"),
	MERCEDES_BENZ___B_KLASS("B-класс"),
	MERCEDES_BENZ___CITAN("Citan"),
	MERCEDES_BENZ___CLA_KLASS("CLA-класс"),
	MERCEDES_BENZ___CLA_KLASS_AMG("CLA-класс AMG"),
	MERCEDES_BENZ___CLC_KLASS("CLC-класс"),
	MERCEDES_BENZ___CLK_KLASS("CLK-класс"),
	MERCEDES_BENZ___CLK_KLASS_AMG("CLK-класс AMG"),
	MERCEDES_BENZ___CLR_KLASS("CLR-класс"),
	MERCEDES_BENZ___CLS_KLASS("CLS-класс"),
	MERCEDES_BENZ___CLS_KLASS_AMG("CLS-класс AMG"),
	MERCEDES_BENZ___CL_KLASS("CL-класс"),
	MERCEDES_BENZ___CL_KLASS_AMG("CL-класс AMG"),
	MERCEDES_BENZ___C_KLASS("C-класс"),
	MERCEDES_BENZ___C_KLASS_AMG("C-класс AMG"),
	MERCEDES_BENZ___E_KLASS("E-класс"),
	MERCEDES_BENZ___E_KLASS_AMG("E-класс AMG"),
	MERCEDES_BENZ___GLA_KLASS("GLA-класс"),
	MERCEDES_BENZ___GLA_KLASS_AMG("GLA-класс AMG"),
	MERCEDES_BENZ___GLE_KLASS("GLE-класс"),
	MERCEDES_BENZ___GLE_KLASS_AMG("GLE-класс AMG"),
	MERCEDES_BENZ___GLK_KLASS("GLK-класс"),
	MERCEDES_BENZ___GL_KLASS("GL-класс"),
	MERCEDES_BENZ___GL_KLASS_AMG("GL-класс AMG"),
	MERCEDES_BENZ___G_KLASS("G-класс"),
	MERCEDES_BENZ___G_KLASS_AMG("G-класс AMG"),
	MERCEDES_BENZ___MAYBACH_S_KLASS("Maybach S-класс"),
	MERCEDES_BENZ___ML_KLASS_AMG("ML-класс AMG"),
	MERCEDES_BENZ___M_KLASS("M-класс"),
	MERCEDES_BENZ___PULLMAN("Pullman"),
	MERCEDES_BENZ___R_KLASS("R-класс"),
	MERCEDES_BENZ___R_KLASS_AMG("R-класс AMG"),
	MERCEDES_BENZ___SLK_KLASS("SLK-класс"),
	MERCEDES_BENZ___SLK_KLASS_AMG("SLK-класс AMG"),
	MERCEDES_BENZ___SLR_MCLAREN("SLR McLaren"),
	MERCEDES_BENZ___SLS_KLASS("SLS-класс"),
	MERCEDES_BENZ___SLS_KLASS_AMG("SLS-класс AMG"),
	MERCEDES_BENZ___SL_KLASS("SL-класс"),
	MERCEDES_BENZ___SL_KLASS_AMG("SL-класс AMG"),
	MERCEDES_BENZ___SPRINTER("Sprinter"),
	MERCEDES_BENZ___SPRINTER_CLASSIC("Sprinter Classic"),
	MERCEDES_BENZ___S_KLASS("S-класс"),
	MERCEDES_BENZ___S_KLASS_AMG("S-класс AMG"),
	MERCEDES_BENZ___VANEO("Vaneo"),
	MERCEDES_BENZ___VARIO("Vario"),
	MERCEDES_BENZ___VIANO("Viano"),
	MERCEDES_BENZ___VITO("Vito"),
	MERCEDES_BENZ___V_KLASS("V-класс"),
	MERCEDES_BENZ___W123("W123"),
	MERCEDES_BENZ___W124("W124"),
	MERCEDES_BENZ___DRUGAYA("Другая"),
	MERCURY___CAPRI("Capri"),
	MERCURY___COUGAR("Cougar"),
	MERCURY___GRAND_MARQUIS("Grand Marquis"),
	MERCURY___MARAUDER("Marauder"),
	MERCURY___MARINER("Mariner"),
	MERCURY___MARQUIS("Marquis"),
	MERCURY___MILAN("Milan"),
	MERCURY___MONTEGO("Montego"),
	MERCURY___MONTEREY("Monterey"),
	MERCURY___MOUNTAINEER("Mountaineer"),
	MERCURY___MYSTIQUE("Mystique"),
	MERCURY___SABLE("Sable"),
	MERCURY___TOPAZ("Topaz"),
	MERCURY___TRACER("Tracer"),
	MERCURY___VILLAGER("Villager"),
	MERCURY___DRUGAYA("Другая"),
	METROCAB___TAXI("Taxi"),
	METROCAB___DRUGAYA("Другая"),
	MG___F("F"),
	MG___TF("TF"),
	MG___XPOWER_SV("XPower SV"),
	MG___ZR("ZR"),
	MG___ZS("ZS"),
	MG___ZT("ZT"),
	MG___DRUGAYA("Другая"),
	MINI___COOPER("Cooper"),
	MINI___COOPER_CLUBMAN("Cooper Clubman"),
	MINI___COOPER_CLUBVAN("Cooper Clubvan"),
	MINI___COOPER_COUNTRYMAN("Cooper Countryman"),
	MINI___COOPER_PACEMAN("Cooper Paceman"),
	MINI___COOPER_S("Cooper S"),
	MINI___COOPER_S_CLUBMAN("Cooper S Clubman"),
	MINI___COOPER_S_COUNTRYMAN("Cooper S Countryman"),
	MINI___COOPER_S_PACEMAN("Cooper S Paceman"),
	MINI___JOHN_COOPER_WORKS("John Cooper Works"),
	MINI___JOHN_COOPER_WORKS_CLUBMAN("John Cooper Works Clubman"),
	MINI___JOHN_COOPER_WORKS_COUNTRYMAN("John Cooper Works Countryman"),
	MINI___JOHN_COOPER_WORKS_PACEMAN("John Cooper Works Paceman"),
	MINI___ONE("One"),
	MINI___ONE_CLUBMAN("One Clubman"),
	MINI___ONE_CLUBVAN("One Clubvan"),
	MINI___ONE_COUNTRYMAN("One Countryman"),
	MINI___DRUGAYA("Другая"),
	MITSUBISHI___3000_GT("3000 GT"),
	MITSUBISHI___AIRTREK("Airtrek"),
	MITSUBISHI___ASPIRE("Aspire"),
	MITSUBISHI___ASX("ASX"),
	MITSUBISHI___CARISMA("Carisma"),
	MITSUBISHI___CELESTE("Celeste"),
	MITSUBISHI___CHALLENGER("Challenger"),
	MITSUBISHI___CHARIOT("Chariot"),
	MITSUBISHI___COLT("Colt"),
	MITSUBISHI___CORDIA("Cordia"),
	MITSUBISHI___DEBONAIR("Debonair"),
	MITSUBISHI___DELICA("Delica"),
	MITSUBISHI___DIAMANTE("Diamante"),
	MITSUBISHI___DINGO("Dingo"),
	MITSUBISHI___DION("Dion"),
	MITSUBISHI___ECLIPSE("Eclipse"),
	MITSUBISHI___EK_WAGON("EK Wagon"),
	MITSUBISHI___EMERAUDE("Emeraude"),
	MITSUBISHI___ENDEAVOR("Endeavor"),
	MITSUBISHI___ETERNA("Eterna"),
	MITSUBISHI___EXPO_LRV("Expo LRV"),
	MITSUBISHI___FTO("FTO"),
	MITSUBISHI___FUSO_CANTER("Fuso Canter"),
	MITSUBISHI___GALANT("Galant"),
	MITSUBISHI___GRANDIS("Grandis"),
	MITSUBISHI___GTO("GTO"),
	MITSUBISHI___I("i"),
	MITSUBISHI___I_MIEV("i-MiEV"),
	MITSUBISHI___JEEP("Jeep"),
	MITSUBISHI___L200("L200"),
	MITSUBISHI___LANCER("Lancer"),
	MITSUBISHI___LANCER_EVOLUTION("Lancer Evolution"),
	MITSUBISHI___LEGNUM("Legnum"),
	MITSUBISHI___LIBERO("Libero"),
	MITSUBISHI___MINICA("Minica"),
	MITSUBISHI___MINICAB("Minicab"),
	MITSUBISHI___MIRAGE("Mirage"),
	MITSUBISHI___MONTERO("Montero"),
	MITSUBISHI___MONTERO_SPORT("Montero Sport"),
	MITSUBISHI___OUTLANDER("Outlander"),
	MITSUBISHI___PAJERO("Pajero"),
	MITSUBISHI___PAJERO_JUNIOR("Pajero Junior"),
	MITSUBISHI___PAJERO_MINI("Pajero Mini"),
	MITSUBISHI___PAJERO_PININ("Pajero Pinin"),
	MITSUBISHI___PAJERO_SPORT("Pajero Sport"),
	MITSUBISHI___PISTACHIO("Pistachio"),
	MITSUBISHI___PROUDIA("Proudia"),
	MITSUBISHI___RAIDER("Raider"),
	MITSUBISHI___RVR("RVR"),
	MITSUBISHI___SANTAMO("Santamo"),
	MITSUBISHI___SAPPORO("Sapporo"),
	MITSUBISHI___SIGMA("Sigma"),
	MITSUBISHI___SPACE_GEAR("Space Gear"),
	MITSUBISHI___SPACE_RUNNER("Space Runner"),
	MITSUBISHI___SPACE_STAR("Space Star"),
	MITSUBISHI___SPACE_WAGON("Space Wagon"),
	MITSUBISHI___STARION("Starion"),
	MITSUBISHI___TOPPO("Toppo"),
	MITSUBISHI___TOWN_BOX("Town BOX"),
	MITSUBISHI___TREDIA("Tredia"),
	MITSUBISHI___DRUGAYA("Другая"),
	MITSUOKA___GALUE("Galue"),
	MITSUOKA___LE_SEYDE("Le-Seyde"),
	MITSUOKA___NOUERA("Nouera"),
	MITSUOKA___RYOGA("Ryoga"),
	MITSUOKA___DRUGAYA("Другая"),
	MORGAN___AERO("Aero"),
	MORGAN___PLUS_4("Plus 4"),
	MORGAN___PLUS_8("Plus 8"),
	MORGAN___V6("V6"),
	MORGAN___DRUGAYA("Другая"),
	MORRIS___MARINA("Marina"),
	MORRIS___DRUGAYA("Другая"),
	NISSAN___100NX("100NX"),
	NISSAN___180SX("180SX"),
	NISSAN___200SX("200SX"),
	NISSAN___240SX("240SX"),
	NISSAN___280_ZX("280 ZX"),
	NISSAN___300ZX("300ZX"),
	NISSAN___350Z("350Z"),
	NISSAN___370Z("370Z"),
	NISSAN___AD("AD"),
	NISSAN___ALMERA("Almera"),
	NISSAN___ALMERA_CLASSIC("Almera Classic"),
	NISSAN___ALTIMA("Altima"),
	NISSAN___ARMADA("Armada"),
	NISSAN___AVENIR("Avenir"),
	NISSAN___BASSARA("Bassara"),
	NISSAN___BLUEBIRD("Bluebird"),
	NISSAN___CEDRIC("Cedric"),
	NISSAN___CEFIRO("Cefiro"),
	NISSAN___CHERRY("Cherry"),
	NISSAN___CIMA("Cima"),
	NISSAN___CLIPPER("Clipper"),
	NISSAN___CREW("Crew"),
	NISSAN___CUBE("Cube"),
	NISSAN___DATSUN("Datsun"),
	NISSAN___ELGRAND("Elgrand"),
	NISSAN___EXPERT("Expert"),
	NISSAN___FAIRLADY("Fairlady"),
	NISSAN___FIGARO("Figaro"),
	NISSAN___FRONTIER("Frontier"),
	NISSAN___FUGA("Fuga"),
	NISSAN___GLORIA("Gloria"),
	NISSAN___GT_R("GT-R"),
	NISSAN___JUKE("Juke"),
	NISSAN___KING_CAB("King Cab"),
	NISSAN___KIX("Kix"),
	NISSAN___LAFESTA("Lafesta"),
	NISSAN___LANGLEY("Langley"),
	NISSAN___LARGO("Largo"),
	NISSAN___LAUREL("Laurel"),
	NISSAN___LEAF("Leaf"),
	NISSAN___LEOPARD("Leopard"),
	NISSAN___LIBERTY("Liberty"),
	NISSAN___LUCINO("Lucino"),
	NISSAN___MARCH("March"),
	NISSAN___MAXIMA("Maxima"),
	NISSAN___MICRA("Micra"),
	NISSAN___MISTRAL("Mistral"),
	NISSAN___MOCO("Moco"),
	NISSAN___MURANO("Murano"),
	NISSAN___NAVARA("Navara"),
	NISSAN___NOTE("Note"),
	NISSAN___NP300("NP300"),
	NISSAN___NX_COUPE("NX Coupe"),
	NISSAN___OTTI("Otti"),
	NISSAN___PATHFINDER("Pathfinder"),
	NISSAN___PATROL("Patrol"),
	NISSAN___PICK_UP("Pick UP"),
	NISSAN___PRAIRIE("Prairie"),
	NISSAN___PRESAGE("Presage"),
	NISSAN___PRESEA("Presea"),
	NISSAN___PRESIDENT("President"),
	NISSAN___PRIMERA("Primera"),
	NISSAN___PULSAR("Pulsar"),
	NISSAN___QASHQAI("Qashqai"),
	NISSAN___QASHQAI2("Qashqai+2"),
	NISSAN___QUEST("Quest"),
	NISSAN___RASHEEN("Rasheen"),
	NISSAN___R_NESSA("R Nessa"),
	NISSAN___ROGUE("Rogue"),
	NISSAN___SAFARI("Safari"),
	NISSAN___SENTRA("Sentra"),
	NISSAN___SERENA("Serena"),
	NISSAN___SILVIA("Silvia"),
	NISSAN___SKYLINE("Skyline"),
	NISSAN___STAGEA("Stagea"),
	NISSAN___STANZA("Stanza"),
	NISSAN___SUNNY("Sunny"),
	NISSAN___TEANA("Teana"),
	NISSAN___TERRANO("Terrano"),
	NISSAN___TIIDA("Tiida"),
	NISSAN___TINO("Tino"),
	NISSAN___TITAN("Titan"),
	NISSAN___VANETTE("Vanette"),
	NISSAN___VERSA("Versa"),
	NISSAN___WINGROAD("Wingroad"),
	NISSAN___X_TERRA("X-Terra"),
	NISSAN___X_TRAIL("X-Trail"),
	NISSAN___DRUGAYA("Другая"),
	NOBLE___M10("M10"),
	NOBLE___M12("M12"),
	NOBLE___M14("M14"),
	NOBLE___M15("M15"),
	NOBLE___M400("M400"),
	NOBLE___M600("M600"),
	NOBLE___DRUGAYA("Другая"),
	OLDSMOBILE___ACHIEVA("Achieva"),
	OLDSMOBILE___ALERO("Alero"),
	OLDSMOBILE___AURORA("Aurora"),
	OLDSMOBILE___BRAVADA("Bravada"),
	OLDSMOBILE___CUTLASS("Cutlass"),
	OLDSMOBILE___EIGHTY_EIGHT("Eighty-Eight"),
	OLDSMOBILE___INTRIGUE("Intrigue"),
	OLDSMOBILE___NINETY_EIGHT("Ninety-Eight"),
	OLDSMOBILE___SILHOUETTE("Silhouette"),
	OLDSMOBILE___DRUGAYA("Другая"),
	OPEL___ADMIRAL("Admiral"),
	OPEL___AGILA("Agila"),
	OPEL___ANTARA("Antara"),
	OPEL___ASCONA("Ascona"),
	OPEL___ASTRA("Astra"),
	OPEL___ASTRA_GTC("Astra GTC"),
	OPEL___ASTRA_OPC("Astra OPC"),
	OPEL___CALIBRA("Calibra"),
	OPEL___CAMPO("Campo"),
	OPEL___COMBO("Combo"),
	OPEL___COMMODORE("Commodore"),
	OPEL___CORSA("Corsa"),
	OPEL___CORSA_OPC("Corsa OPC"),
	OPEL___DIPLOMAT("Diplomat"),
	OPEL___FRONTERA("Frontera"),
	OPEL___GT("GT"),
	OPEL___INSIGNIA("Insignia"),
	OPEL___INSIGNIA_OPC("Insignia OPC"),
	OPEL___KADETT("Kadett"),
	OPEL___MANTA("Manta"),
	OPEL___MERIVA("Meriva"),
	OPEL___MOKKA("Mokka"),
	OPEL___MONTEREY("Monterey"),
	OPEL___MONZA("Monza"),
	OPEL___MOVANO("Movano"),
	OPEL___OMEGA("Omega"),
	OPEL___REKORD("Rekord"),
	OPEL___SENATOR("Senator"),
	OPEL___SIGNUM("Signum"),
	OPEL___SINTRA("Sintra"),
	OPEL___SPEEDSTER("Speedster"),
	OPEL___TIGRA("Tigra"),
	OPEL___VECTRA("Vectra"),
	OPEL___VITA("Vita"),
	OPEL___VIVARO("Vivaro"),
	OPEL___ZAFIRA("Zafira"),
	OPEL___DRUGAYA("Другая"),
	PAGANI___HUAYRA("Huayra"),
	PAGANI___ZONDA("Zonda"),
	PAGANI___DRUGAYA("Другая"),
	PEUGEOT___1007("1007"),
	PEUGEOT___104("104"),
	PEUGEOT___106("106"),
	PEUGEOT___107("107"),
	PEUGEOT___2008("2008"),
	PEUGEOT___204("204"),
	PEUGEOT___205("205"),
	PEUGEOT___206("206"),
	PEUGEOT___207("207"),
	PEUGEOT___208("208"),
	PEUGEOT___3008("3008"),
	PEUGEOT___301("301"),
	PEUGEOT___304("304"),
	PEUGEOT___305("305"),
	PEUGEOT___306("306"),
	PEUGEOT___307("307"),
	PEUGEOT___308("308"),
	PEUGEOT___309("309"),
	PEUGEOT___4007("4007"),
	PEUGEOT___4008("4008"),
	PEUGEOT___405("405"),
	PEUGEOT___406("406"),
	PEUGEOT___407("407"),
	PEUGEOT___408("408"),
	PEUGEOT___5008("5008"),
	PEUGEOT___504("504"),
	PEUGEOT___505("505"),
	PEUGEOT___508("508"),
	PEUGEOT___604("604"),
	PEUGEOT___605("605"),
	PEUGEOT___607("607"),
	PEUGEOT___806("806"),
	PEUGEOT___807("807"),
	PEUGEOT___BIPPER("Bipper"),
	PEUGEOT___BOXER("Boxer"),
	PEUGEOT___EXPERT("Expert"),
	PEUGEOT___PARTNER("Partner"),
	PEUGEOT___RCZ("RCZ"),
	PEUGEOT___DRUGAYA("Другая"),
	PLYMOUTH___ACCLAIM("Acclaim"),
	PLYMOUTH___BREEZE("Breeze"),
	PLYMOUTH___CARAVELLE("Caravelle"),
	PLYMOUTH___GRAND_VOYAGER("Grand Voyager"),
	PLYMOUTH___LASER("Laser"),
	PLYMOUTH___NEON("Neon"),
	PLYMOUTH___PROWLER("Prowler"),
	PLYMOUTH___SUNDANCE("Sundance"),
	PLYMOUTH___VOYAGER("Voyager"),
	PLYMOUTH___DRUGAYA("Другая"),
	PONTIAC___6000("6000"),
	PONTIAC___AZTEC("Aztec"),
	PONTIAC___BONNEVILLE("Bonneville"),
	PONTIAC___FIERO("Fiero"),
	PONTIAC___FIREBIRD("Firebird"),
	PONTIAC___G4("G4"),
	PONTIAC___G5("G5"),
	PONTIAC___G6("G6"),
	PONTIAC___G8("G8"),
	PONTIAC___GRAND_AM("Grand AM"),
	PONTIAC___GRAND_PRIX("Grand Prix"),
	PONTIAC___GTO("GTO"),
	PONTIAC___LEMANS("LeMans"),
	PONTIAC___MONTANA("Montana"),
	PONTIAC___PARISIENNE("Parisienne"),
	PONTIAC___PHOENIX("Phoenix"),
	PONTIAC___SOLSTICE("Solstice"),
	PONTIAC___SUNBIRD("Sunbird"),
	PONTIAC___SUNFIRE("Sunfire"),
	PONTIAC___TEMPEST("Tempest"),
	PONTIAC___TORRENT("Torrent"),
	PONTIAC___TRANS_SPORT("Trans Sport"),
	PONTIAC___VIBE("Vibe"),
	PONTIAC___DRUGAYA("Другая"),
	PORSCHE___356("356"),
	PORSCHE___911_CARRERA("911 Carrera"),
	PORSCHE___911_CARRERA_4("911 Carrera 4"),
	PORSCHE___911_CARRERA_4S("911 Carrera 4S"),
	PORSCHE___911_CARRERA_S("911 Carrera S"),
	PORSCHE___911_GT2("911 GT2"),
	PORSCHE___911_GT2_RS("911 GT2 RS"),
	PORSCHE___911_GT3("911 GT3"),
	PORSCHE___911_GT3_RS("911 GT3 RS"),
	PORSCHE___911_GT3_RS_40("911 GT3 RS 4.0"),
	PORSCHE___911_TARGA_4("911 Targa 4"),
	PORSCHE___911_TARGA_4S("911 Targa 4S"),
	PORSCHE___911_TURBO("911 Turbo"),
	PORSCHE___911_TURBO_S("911 Turbo S"),
	PORSCHE___918_SPYDER("918 Spyder"),
	PORSCHE___924("924"),
	PORSCHE___928("928"),
	PORSCHE___944("944"),
	PORSCHE___959("959"),
	PORSCHE___968("968"),
	PORSCHE___BOXSTER("Boxster"),
	PORSCHE___BOXSTER_S("Boxster S"),
	PORSCHE___BOXSTER_SPYDER("Boxster Spyder"),
	PORSCHE___CARRERA_GT("Carrera GT"),
	PORSCHE___CAYENNE("Cayenne"),
	PORSCHE___CAYENNE_GTS("Cayenne GTS"),
	PORSCHE___CAYENNE_S("Cayenne S"),
	PORSCHE___CAYENNE_TURBO("Cayenne Turbo"),
	PORSCHE___CAYENNE_TURBO_S("Cayenne Turbo S"),
	PORSCHE___CAYMAN("Cayman"),
	PORSCHE___CAYMAN_S("Cayman S"),
	PORSCHE___MACAN_S("Macan S"),
	PORSCHE___MACAN_TURBO("Macan Turbo"),
	PORSCHE___PANAMERA("Panamera"),
	PORSCHE___PANAMERA_4("Panamera 4"),
	PORSCHE___PANAMERA_4S("Panamera 4S"),
	PORSCHE___PANAMERA_GTS("Panamera GTS"),
	PORSCHE___PANAMERA_S("Panamera S"),
	PORSCHE___PANAMERA_TURBO("Panamera Turbo"),
	PORSCHE___DRUGAYA("Другая"),
	PROTON___JUARA("Juara"),
	PROTON___PERDANA("Perdana"),
	PROTON___PERSONA("Persona"),
	PROTON___SAGA("Saga"),
	PROTON___SALOON("Saloon"),
	PROTON___WAJA("Waja"),
	PROTON___DRUGAYA("Другая"),
	RENAULT___11("11"),
	RENAULT___12("12"),
	RENAULT___14("14"),
	RENAULT___15("15"),
	RENAULT___16("16"),
	RENAULT___17("17"),
	RENAULT___18("18"),
	RENAULT___19("19"),
	RENAULT___20("20"),
	RENAULT___21("21"),
	RENAULT___25("25"),
	RENAULT___30("30"),
	RENAULT___4("4"),
	RENAULT___5("5"),
	RENAULT___6("6"),
	RENAULT___9("9"),
	RENAULT___AVANTIME("Avantime"),
	RENAULT___CLIO("Clio"),
	RENAULT___CLIO_RS("Clio RS"),
	RENAULT___DUSTER("Duster"),
	RENAULT___ESPACE("Espace"),
	RENAULT___ESTAFETTE("Estafette"),
	RENAULT___FLUENCE("Fluence"),
	RENAULT___FUEGO("Fuego"),
	RENAULT___GRAND_SCENIC("Grand Scenic"),
	RENAULT___KANGOO("Kangoo"),
	RENAULT___KOLEOS("Koleos"),
	RENAULT___LAGUNA("Laguna"),
	RENAULT___LATITUDE("Latitude"),
	RENAULT___LOGAN("Logan"),
	RENAULT___MASTER("Master"),
	RENAULT___MEDALLION("Medallion"),
	RENAULT___MEGANE("Megane"),
	RENAULT___MEGANE_RS("Megane RS"),
	RENAULT___MODUS("Modus"),
	RENAULT___RAPID("Rapid"),
	RENAULT___RODEO("Rodeo"),
	RENAULT___SAFRANE("Safrane"),
	RENAULT___SANDERO("Sandero"),
	RENAULT___SANDERO_STEPWAY("Sandero Stepway"),
	RENAULT___SCENIC("Scenic"),
	RENAULT___SPORT_SPIDER("Sport Spider"),
	RENAULT___SUPER_5("Super 5"),
	RENAULT___SYMBOL("Symbol"),
	RENAULT___TRAFIC("Trafic"),
	RENAULT___TWINGO("Twingo"),
	RENAULT___TWIZY("Twizy"),
	RENAULT___VEL_SATIS("Vel Satis"),
	RENAULT___WIND("Wind"),
	RENAULT___DRUGAYA("Другая"),
	ROLLS_ROYCE___CORNICHE_CABRIO("Corniche Cabrio"),
	ROLLS_ROYCE___GHOST("Ghost"),
	ROLLS_ROYCE___PARK_WARD("Park Ward"),
	ROLLS_ROYCE___PHANTOM("Phantom"),
	ROLLS_ROYCE___SILVER_SERAPH("Silver Seraph"),
	ROLLS_ROYCE___SILVER_SPUR("Silver Spur"),
	ROLLS_ROYCE___WRAITH("Wraith"),
	ROLLS_ROYCE___DRUGAYA("Другая"),
	RONART___LIGHTNING("Lightning"),
	RONART___DRUGAYA("Другая"),
	ROVER___100("100"),
	ROVER___200("200"),
	ROVER___25("25"),
	ROVER___400("400"),
	ROVER___45("45"),
	ROVER___600("600"),
	ROVER___75("75"),
	ROVER___800("800"),
	ROVER___MAESTRO("Maestro"),
	ROVER___MGF("MGF"),
	ROVER___MINI_MK("Mini MK"),
	ROVER___MONTEGO("Montego"),
	ROVER___STREETWISE("Streetwise"),
	ROVER___DRUGAYA("Другая"),
	SAAB___90("90"),
	SAAB___900("900"),
	SAAB___9000("9000"),
	SAAB___9_2X("9-2X"),
	SAAB___9_3("9-3"),
	SAAB___9_4("9-4"),
	SAAB___95("95"),
	SAAB___9_5("9-5"),
	SAAB___96("96"),
	SAAB___9_7X("9-7X"),
	SAAB___99("99"),
	SAAB___DRUGAYA("Другая"),
	SALEEN___S7("S7"),
	SALEEN___DRUGAYA("Другая"),
	SATURN___ASTRA("Astra"),
	SATURN___AURA("Aura"),
	SATURN___ION("ION"),
	SATURN___LS("LS"),
	SATURN___LW("LW"),
	SATURN___OUTLOOK("Outlook"),
	SATURN___RELAY("Relay"),
	SATURN___SC("SC"),
	SATURN___SKY("Sky"),
	SATURN___SL("SL"),
	SATURN___SW("SW"),
	SATURN___VUE("VUE"),
	SATURN___DRUGAYA("Другая"),
	SCION___TC("tC"),
	SCION___XA("xA"),
	SCION___XB("xB"),
	SCION___XD("xD"),
	SCION___DRUGAYA("Другая"),
	SEAT___ALHAMBRA("Alhambra"),
	SEAT___ALTEA("Altea"),
	SEAT___ALTEA_FREETRACK("Altea Freetrack"),
	SEAT___ALTEA_XL("Altea XL"),
	SEAT___AROSA("Arosa"),
	SEAT___CORDOBA("Cordoba"),
	SEAT___EXEO("Exeo"),
	SEAT___FURA("Fura"),
	SEAT___IBIZA("Ibiza"),
	SEAT___IBIZA_FR("Ibiza FR"),
	SEAT___LEON("Leon"),
	SEAT___LEON_FR("Leon FR"),
	SEAT___MALAGA("Malaga"),
	SEAT___MARBELLA("Marbella"),
	SEAT___MII("Mii"),
	SEAT___RONDA("Ronda"),
	SEAT___TERRA("Terra"),
	SEAT___TOLEDO("Toledo"),
	SEAT___DRUGAYA("Другая"),
	SHUANGHUAN___SCEO("Sceo"),
	SHUANGHUAN___DRUGAYA("Другая"),
	SKODA___CITIGO("Citigo"),
	SKODA___FABIA("Fabia"),
	SKODA___FABIA_RS("Fabia RS"),
	SKODA___FABIA_SCOUT("Fabia Scout"),
	SKODA___FAVORIT("Favorit"),
	SKODA___FELICIA("Felicia"),
	SKODA___OCTAVIA("Octavia"),
	SKODA___OCTAVIA_RS("Octavia RS"),
	SKODA___OCTAVIA_SCOUT("Octavia Scout"),
	SKODA___PRAKTIK("Praktik"),
	SKODA___RAPID("Rapid"),
	SKODA___ROOMSTER("Roomster"),
	SKODA___ROOMSTER_SCOUT("Roomster Scout"),
	SKODA___SUPERB("Superb"),
	SKODA___YETI("Yeti"),
	SKODA___DRUGAYA("Другая"),
	SMA___C32("C32"),
	SMA___C51("C51"),
	SMA___C52("C52"),
	SMA___C61("C61"),
	SMA___C81("C81"),
	SMA___DRUGAYA("Другая"),
	SMART___CROSSBLADE("Crossblade"),
	SMART___FORFOUR("Forfour"),
	SMART___FORTWO("Fortwo"),
	SMART___ROADSTER("Roadster"),
	SMART___DRUGAYA("Другая"),
	SPYKER___C8("C8"),
	SPYKER___DRUGAYA("Другая"),
	SSANGYONG___ACTYON("Actyon"),
	SSANGYONG___CHAIRMAN("Chairman"),
	SSANGYONG___FAMILY("Family"),
	SSANGYONG___ISTANA("Istana"),
	SSANGYONG___KALLISTA("Kallista"),
	SSANGYONG___KORANDO("Korando"),
	SSANGYONG___KYRON("Kyron"),
	SSANGYONG___MUSSO("Musso"),
	SSANGYONG___REXTON("Rexton"),
	SSANGYONG___RODIUS("Rodius"),
	SSANGYONG___STAVIC("Stavic"),
	SSANGYONG___TAGER("Tager"),
	SSANGYONG___DRUGAYA("Другая"),
	SUBARU___ALCYONE("Alcyone"),
	SUBARU___BAJA("Baja"),
	SUBARU___BISTRO("Bistro"),
	SUBARU___BRZ("BRZ"),
	SUBARU___DEX("Dex"),
	SUBARU___DIAS("Dias"),
	SUBARU___DOMINGO("Domingo"),
	SUBARU___EXIGA("Exiga"),
	SUBARU___FORESTER("Forester"),
	SUBARU___IMPREZA("Impreza"),
	SUBARU___JUSTY("Justy"),
	SUBARU___LEGACY("Legacy"),
	SUBARU___LEONE("Leone"),
	SUBARU___LIBERO("Libero"),
	SUBARU___LUCRA("Lucra"),
	SUBARU___OUTBACK("Outback"),
	SUBARU___PLEO("Pleo"),
	SUBARU___R1("R1"),
	SUBARU___R2("R2"),
	SUBARU___SAMBAR("Sambar"),
	SUBARU___STELLA("Stella"),
	SUBARU___SVX("SVX"),
	SUBARU___TRAVIQ("Traviq"),
	SUBARU___TREZIA("Trezia"),
	SUBARU___TRIBECA("Tribeca"),
	SUBARU___VIVIO("Vivio"),
	SUBARU___WRX("WRX"),
	SUBARU___WRX_STI("WRX STI"),
	SUBARU___XT("XT"),
	SUBARU___XV("XV"),
	SUBARU___DRUGAYA("Другая"),
	SUZUKI___AERIO("Aerio"),
	SUZUKI___ALTO("Alto"),
	SUZUKI___BALENO("Baleno"),
	SUZUKI___CAPPUCCINO("Cappuccino"),
	SUZUKI___CERVO("Cervo"),
	SUZUKI___CULTUS_WAGON("Cultus Wagon"),
	SUZUKI___ESCUDO("Escudo"),
	SUZUKI___EVERY("Every"),
	SUZUKI___EVERY_LANDY("Every Landy"),
	SUZUKI___FORENZA("Forenza"),
	SUZUKI___GRAND_ESCUDO("Grand Escudo"),
	SUZUKI___GRAND_VITARA("Grand Vitara"),
	SUZUKI___IGNIS("Ignis"),
	SUZUKI___JIMNY("Jimny"),
	SUZUKI___KEI("Kei"),
	SUZUKI___KIZASHI("Kizashi"),
	SUZUKI___LIANA("Liana"),
	SUZUKI___MR_WAGON("MR Wagon"),
	SUZUKI___RENO("Reno"),
	SUZUKI___SAMURAI("Samurai"),
	SUZUKI___SIDEKICK("Sidekick"),
	SUZUKI___SPLASH("Splash"),
	SUZUKI___SWIFT("Swift"),
	SUZUKI___SX4("SX4"),
	SUZUKI___VERONA("Verona"),
	SUZUKI___VITARA("Vitara"),
	SUZUKI___WAGON_R("Wagon R"),
	SUZUKI___X_90("X-90"),
	SUZUKI___XL7("XL7"),
	SUZUKI___DRUGAYA("Другая"),
	TALBOT___ALPINE("Alpine"),
	TALBOT___AVENGER("Avenger"),
	TALBOT___EXPRESS("Express"),
	TALBOT___HORIZON("Horizon"),
	TALBOT___MATRA_BAGHEERA("Matra Bagheera"),
	TALBOT___MINX("Minx"),
	TALBOT___MURENA("Murena"),
	TALBOT___RANCHO("Rancho"),
	TALBOT___RAPIER("Rapier"),
	TALBOT___SAMBA("Samba"),
	TALBOT___SIMCA("Simca"),
	TALBOT___SOLARA("Solara"),
	TALBOT___TAGORA("Tagora"),
	TALBOT___DRUGAYA("Другая"),
	TATA___ARIA("Aria"),
	TATA___ESTATE("Estate"),
	TATA___INDICA("Indica"),
	TATA___INDIGO("Indigo"),
	TATA___MINT("Mint"),
	TATA___SAFARI("Safari"),
	TATA___SIERRA("Sierra"),
	TATA___SUMO("Sumo"),
	TATA___DRUGAYA("Другая"),
	TESLA___MODEL_S("Model S"),
	TESLA___MODEL_X("Model X"),
	TESLA___ROADSTER("Roadster"),
	TESLA___DRUGAYA("Другая"),
	TIANMA___CENTURY("Century"),
	TIANMA___DRUGAYA("Другая"),
	TIANYE___ADMIRAL("Admiral"),
	TIANYE___DRUGAYA("Другая"),
	TOYOTA___4RUNNER("4Runner"),
	TOYOTA___ALLEX("Allex"),
	TOYOTA___ALLION("Allion"),
	TOYOTA___ALPHARD("Alphard"),
	TOYOTA___ALTEZZA("Altezza"),
	TOYOTA___ARISTO("Aristo"),
	TOYOTA___AURION("Aurion"),
	TOYOTA___AURIS("Auris"),
	TOYOTA___AVALON("Avalon"),
	TOYOTA___AVENSIS("Avensis"),
	TOYOTA___AYGO("Aygo"),
	TOYOTA___BB("bB"),
	TOYOTA___BELTA("Belta"),
	TOYOTA___BLADE("Blade"),
	TOYOTA___BLIZZARD("Blizzard"),
	TOYOTA___BREVIS("Brevis"),
	TOYOTA___CALDINA("Caldina"),
	TOYOTA___CAMI("Cami"),
	TOYOTA___CAMRY("Camry"),
	TOYOTA___CARINA("Carina"),
	TOYOTA___CAVALIER("Cavalier"),
	TOYOTA___CELICA("Celica"),
	TOYOTA___CELSIOR("Celsior"),
	TOYOTA___CENTURY("Century"),
	TOYOTA___CHASER("Chaser"),
	TOYOTA___COROLLA("Corolla"),
	TOYOTA___CORONA("Corona"),
	TOYOTA___CORSA("Corsa"),
	TOYOTA___CRESSIDA("Cressida"),
	TOYOTA___CRESTA("Cresta"),
	TOYOTA___CROWN("Crown"),
	TOYOTA___CURREN("Curren"),
	TOYOTA___CYNOS("Cynos"),
	TOYOTA___DUET("Duet"),
	TOYOTA___ECHO("Echo"),
	TOYOTA___ESTIMA("Estima"),
	TOYOTA___FJ_CRUISER("FJ Cruiser"),
	TOYOTA___FORTUNER("Fortuner"),
	TOYOTA___FUNCARGO("Funcargo"),
	TOYOTA___GAIA("Gaia"),
	TOYOTA___GRAND_HIACE("Grand Hiace"),
	TOYOTA___GRANVIA("Granvia"),
	TOYOTA___GT_86("GT 86"),
	TOYOTA___HARRIER("Harrier"),
	TOYOTA___HIACE("Hiace"),
	TOYOTA___HIGHLANDER("Highlander"),
	TOYOTA___HILUX("Hilux"),
	TOYOTA___INNOVA("Innova"),
	TOYOTA___IPSUM("Ipsum"),
	TOYOTA___IQ("iQ"),
	TOYOTA___ISIS("Isis"),
	TOYOTA___IST("Ist"),
	TOYOTA___KLUGER("Kluger"),
	TOYOTA___LAND_CRUISER("Land Cruiser"),
	TOYOTA___LAND_CRUISER_PRADO("Land Cruiser Prado"),
	TOYOTA___LITE_ACE("Lite Ace"),
	TOYOTA___MARK_II("Mark II"),
	TOYOTA___MARK_X("Mark X"),
	TOYOTA___MARK_X_ZIO("Mark X ZiO"),
	TOYOTA___MASTERACE("MasterAce"),
	TOYOTA___MATRIX("Matrix"),
	TOYOTA___MEGA_CRUISER("Mega Cruiser"),
	TOYOTA___MR2("MR2"),
	TOYOTA___MR_S("MR-S"),
	TOYOTA___NADIA("Nadia"),
	TOYOTA___NOAH("Noah"),
	TOYOTA___OPA("Opa"),
	TOYOTA___ORIGIN("Origin"),
	TOYOTA___PASEO("Paseo"),
	TOYOTA___PASSO("Passo"),
	TOYOTA___PASSO_SETTE("Passo Sette"),
	TOYOTA___PICNIC("Picnic"),
	TOYOTA___PLATZ("Platz"),
	TOYOTA___PORTE("Porte"),
	TOYOTA___PREMIO("Premio"),
	TOYOTA___PREVIA("Previa"),
	TOYOTA___PRIUS("Prius"),
	TOYOTA___PROBOX("Probox"),
	TOYOTA___PROGRES("Progres"),
	TOYOTA___PRONARD("Pronard"),
	TOYOTA___RACTIS("Ractis"),
	TOYOTA___RAUM("Raum"),
	TOYOTA___RAV4("RAV4"),
	TOYOTA___REGIUS("Regius"),
	TOYOTA___RUSH("Rush"),
	TOYOTA___SAI("SAI"),
	TOYOTA___SCEPTER("Scepter"),
	TOYOTA___SEQUOIA("Sequoia"),
	TOYOTA___SERA("Sera"),
	TOYOTA___SIENNA("Sienna"),
	TOYOTA___SIENTA("Sienta"),
	TOYOTA___SOARER("Soarer"),
	TOYOTA___SOLARA("Solara"),
	TOYOTA___SOLUNA("Soluna"),
	TOYOTA___SPARKY("Sparky"),
	TOYOTA___SPRINTER("Sprinter"),
	TOYOTA___SPRINTER_CARIB("Sprinter Carib"),
	TOYOTA___STARLET("Starlet"),
	TOYOTA___SUCCEED("Succeed"),
	TOYOTA___SUPRA("Supra"),
	TOYOTA___TACOMA("Tacoma"),
	TOYOTA___TERCEL("Tercel"),
	TOYOTA___TOWN_ACE("Town Ace"),
	TOYOTA___TUNDRA("Tundra"),
	TOYOTA___URBAN_CRUISER("Urban Cruiser"),
	TOYOTA___VELLFIRE("Vellfire"),
	TOYOTA___VENZA("Venza"),
	TOYOTA___VEROSSA("Verossa"),
	TOYOTA___VERSO("Verso"),
	TOYOTA___VIOS("Vios"),
	TOYOTA___VISTA("Vista"),
	TOYOTA___VITZ("Vitz"),
	TOYOTA___VOLTZ("Voltz"),
	TOYOTA___VOXY("Voxy"),
	TOYOTA___WILL("WiLL"),
	TOYOTA___WINDOM("Windom"),
	TOYOTA___WISH("Wish"),
	TOYOTA___YARIS("Yaris"),
	TOYOTA___DRUGAYA("Другая"),
	TRABANT___11("1.1"),
	TRABANT___P601("P601"),
	TRABANT___DRUGAYA("Другая"),
	VOLKSWAGEN___AMAROK("Amarok"),
	VOLKSWAGEN___BEETLE("Beetle"),
	VOLKSWAGEN___BORA("Bora"),
	VOLKSWAGEN___CADDY("Caddy"),
	VOLKSWAGEN___CALIFORNIA("California"),
	VOLKSWAGEN___CARAVELLE("Caravelle"),
	VOLKSWAGEN___CORRADO("Corrado"),
	VOLKSWAGEN___CRAFTER("Crafter"),
	VOLKSWAGEN___CROSSPOLO("CrossPolo"),
	VOLKSWAGEN___DERBY("Derby"),
	VOLKSWAGEN___EOS("Eos"),
	VOLKSWAGEN___FOX("Fox"),
	VOLKSWAGEN___GOLF("Golf"),
	VOLKSWAGEN___GOLF_COUNTRY("Golf Country"),
	VOLKSWAGEN___GOLF_GTI("Golf GTI"),
	VOLKSWAGEN___GOLF_PLUS("Golf Plus"),
	VOLKSWAGEN___GOLF_R("Golf R"),
	VOLKSWAGEN___ILTIS("Iltis"),
	VOLKSWAGEN___JETTA("Jetta"),
	VOLKSWAGEN___KAEFER("Kaefer"),
	VOLKSWAGEN___LUPO("Lupo"),
	VOLKSWAGEN___MULTIVAN("Multivan"),
	VOLKSWAGEN___NEW_BEETLE("New Beetle"),
	VOLKSWAGEN___PASSAT("Passat"),
	VOLKSWAGEN___PASSAT_CC("Passat CC"),
	VOLKSWAGEN___PHAETON("Phaeton"),
	VOLKSWAGEN___POINTER("Pointer"),
	VOLKSWAGEN___POLO("Polo"),
	VOLKSWAGEN___ROUTAN("Routan"),
	VOLKSWAGEN___SANTANA("Santana"),
	VOLKSWAGEN___SCIROCCO("Scirocco"),
	VOLKSWAGEN___SHARAN("Sharan"),
	VOLKSWAGEN___TARO("Taro"),
	VOLKSWAGEN___TIGUAN("Tiguan"),
	VOLKSWAGEN___TOUAREG("Touareg"),
	VOLKSWAGEN___TOURAN("Touran"),
	VOLKSWAGEN___TRANSPORTER("Transporter"),
	VOLKSWAGEN___UP("Up"),
	VOLKSWAGEN___VENTO("Vento"),
	VOLKSWAGEN___DRUGAYA("Другая"),
	VOLVO___140("140"),
	VOLVO___164("164"),
	VOLVO___240("240"),
	VOLVO___260("260"),
	VOLVO___340("340"),
	VOLVO___360("360"),
	VOLVO___440("440"),
	VOLVO___460("460"),
	VOLVO___480("480"),
	VOLVO___66("66"),
	VOLVO___740("740"),
	VOLVO___760("760"),
	VOLVO___780("780"),
	VOLVO___850("850"),
	VOLVO___940("940"),
	VOLVO___960("960"),
	VOLVO___C30("C30"),
	VOLVO___C70("C70"),
	VOLVO___LAPLANDER("Laplander"),
	VOLVO___S40("S40"),
	VOLVO___S60("S60"),
	VOLVO___S70("S70"),
	VOLVO___S80("S80"),
	VOLVO___S90("S90"),
	VOLVO___V40("V40"),
	VOLVO___V40_CROSS_COUNTRY("V40 Cross Country"),
	VOLVO___V50("V50"),
	VOLVO___V60("V60"),
	VOLVO___V70("V70"),
	VOLVO___V90("V90"),
	VOLVO___XC60("XC60"),
	VOLVO___XC70("XC70"),
	VOLVO___XC90("XC90"),
	VOLVO___DRUGAYA("Другая"),
	VORTEX___CORDA("Corda"),
	VORTEX___ESTINA("Estina"),
	VORTEX___TINGO("Tingo"),
	VORTEX___DRUGAYA("Другая"),
	WARTBURG___353("353"),
	WARTBURG___DRUGAYA("Другая"),
	WIESMANN___GT("GT"),
	WIESMANN___ROADSTER("Roadster"),
	WIESMANN___DRUGAYA("Другая"),
	XIN_KAI___PICKUP_X3("Pickup X3"),
	XIN_KAI___SR_V_X3("SR-V X3"),
	XIN_KAI___SUV_X3("SUV X3"),
	XIN_KAI___DRUGAYA("Другая"),
	ZX___ADMIRAL("Admiral"),
	ZX___GRANDTIGER("GrandTiger"),
	ZX___LANDMARK("Landmark"),
	ZX___DRUGAYA("Другая"),
	VAZ_LADA___1111_OKA("1111 Ока"),
	VAZ_LADA___2101("2101"),
	VAZ_LADA___2102("2102"),
	VAZ_LADA___2103("2103"),
	VAZ_LADA___2104("2104"),
	VAZ_LADA___2105("2105"),
	VAZ_LADA___2106("2106"),
	VAZ_LADA___2107("2107"),
	VAZ_LADA___2108("2108"),
	VAZ_LADA___2109("2109"),
	VAZ_LADA___21099("21099"),
	VAZ_LADA___2110("2110"),
	VAZ_LADA___2111("2111"),
	VAZ_LADA___2112("2112"),
	VAZ_LADA___2113_SAMARA("2113 Samara"),
	VAZ_LADA___2114_SAMARA("2114 Samara"),
	VAZ_LADA___2115_SAMARA("2115 Samara"),
	VAZ_LADA___2120_NADEZHDA("2120 Надежда"),
	VAZ_LADA___2123("2123"),
	VAZ_LADA___2129("2129"),
	VAZ_LADA___2328("2328"),
	VAZ_LADA___2329("2329"),
	VAZ_LADA___4X4_NIVA("4x4 (Нива)"),
	VAZ_LADA___GRANTA("Granta"),
	VAZ_LADA___KALINA("Kalina"),
	VAZ_LADA___LARGUS("Largus"),
	VAZ_LADA___PRIORA("Priora"),
	VAZ_LADA___DRUGAYA("Другая"),
	VIS___1705("1705"),
	VIS___1706("1706"),
	VIS___2345("2345"),
	VIS___2346("2346"),
	VIS___2347("2347"),
	VIS___2349("2349"),
	VIS___DRUGAYA("Другая"),
	GAZ___12_ZIM("12 ЗИМ"),
	GAZ___13_CHAЙKA("13 Чайка"),
	GAZ___14_CHAЙKA("14 Чайка"),
	GAZ___20_POBEDA("20 Победа"),
	GAZ___21_VOLGA("21 Волга"),
	GAZ___22("22"),
	GAZ___24_VOLGA("24 Волга"),
	GAZ___3101_VOLGA("3101 Волга"),
	GAZ___310221_VOLGA("310221 Волга"),
	GAZ___31029_VOLGA("31029 Волга"),
	GAZ___3102_VOLGA("3102 Волга"),
	GAZ___31105_VOLGA("31105 Волга"),
	GAZ___3110_VOLGA("3110 Волга"),
	GAZ___3111_VOLGA("3111 Волга"),
	GAZ___69("69"),
	GAZ___M_1("M-1"),
	GAZ___VOLGA_SIBER("Volga Siber"),
	GAZ___GAZEL("ГАЗель"),
	GAZ___GAZEL_2705("ГАЗель 2705"),
	GAZ___GAZEL_3221("ГАЗель 3221"),
	GAZ___GAZEL_3302("ГАЗель 3302"),
	GAZ___GAZEL_33023("ГАЗель 33023"),
	GAZ___GAZEL_33025("ГАЗель 33025"),
	GAZ___GAZEL_NEXT("ГАЗель Next"),
	GAZ___GAZEL_BIZNES("ГАЗель Бизнес"),
	GAZ___SOBOL("Соболь"),
	GAZ___SOBOL_2217("Соболь 2217"),
	GAZ___SOBOL_2310("Соболь 2310"),
	GAZ___SOBOL_2752("Соболь 2752"),
	GAZ___DRUGAYA("Другая"),
	ZAZ___1102_TAVRIYA("1102 Таврия"),
	ZAZ___1103_SLAVUTA("1103 Славута"),
	ZAZ___1105_DANA("1105 Дана"),
	ZAZ___1125("1125"),
	ZAZ___1140("1140"),
	ZAZ___965("965"),
	ZAZ___966_ZAPOROZHETS("966 Запорожец"),
	ZAZ___968_ZAPOROZHETS("968 Запорожец"),
	ZAZ___CHANCE("Chance"),
	ZAZ___FORZA("Forza"),
	ZAZ___SENS("Sens"),
	ZAZ___VIDA("Vida"),
	ZAZ___DRUGAYA("Другая"),
	ZIL___101("101"),
	ZIL___110("110"),
	ZIL___111("111"),
	ZIL___114("114"),
	ZIL___117("117"),
	ZIL___4104("4104"),
	ZIL___4105("4105"),
	ZIL___4107("4107"),
	ZIL___DRUGAYA("Другая"),
	IZH___2125("2125"),
	IZH___2126("2126"),
	IZH___2715("2715"),
	IZH___2717("2717"),
	IZH___DRUGAYA("Другая"),
	LUAZ___967("967"),
	LUAZ___969("969"),
	LUAZ___DRUGAYA("Другая"),
	MOSKVICH___2136("2136"),
	MOSKVICH___2137("2137"),
	MOSKVICH___2138("2138"),
	MOSKVICH___2140("2140"),
	MOSKVICH___2141("2141"),
	MOSKVICH___2335("2335"),
	MOSKVICH___2733("2733"),
	MOSKVICH___2734("2734"),
	MOSKVICH___400("400"),
	MOSKVICH___401("401"),
	MOSKVICH___402("402"),
	MOSKVICH___403("403"),
	MOSKVICH___407("407"),
	MOSKVICH___408("408"),
	MOSKVICH___410("410"),
	MOSKVICH___411("411"),
	MOSKVICH___412("412"),
	MOSKVICH___420("420"),
	MOSKVICH___422("422"),
	MOSKVICH___423("423"),
	MOSKVICH___424("424"),
	MOSKVICH___426("426"),
	MOSKVICH___427("427"),
	MOSKVICH___430("430"),
	MOSKVICH___432("432"),
	MOSKVICH___433("433"),
	MOSKVICH___434("434"),
	MOSKVICH___DUET("Дуэт"),
	MOSKVICH___IVAN_KALITA("Иван Калита"),
	MOSKVICH___KNYAZЬ_VLADIMIR("Князь Владимир"),
	MOSKVICH___SVYATOGOR("Святогор"),
	MOSKVICH___YURIY_DOLGORUKIY("Юрий Долгорукий"),
	MOSKVICH___DRUGAYA("Другая"),
	RAF___2203("2203"),
	RAF___977("977"),
	RAF___DRUGAYA("Другая"),
	TAGAZ___AQUILA("Aquila"),
	TAGAZ___C10("C10"),
	TAGAZ___C190("C190"),
	TAGAZ___HYUNDAI_ACCENT("Hyundai Accent"),
	TAGAZ___HYUNDAI_SANTA_FE_CLASSIC("Hyundai Santa Fe Classic"),
	TAGAZ___HYUNDAI_SONATA("Hyundai Sonata"),
	TAGAZ___ROAD_PARTNER("Road Partner"),
	TAGAZ___TAGER("Tager"),
	TAGAZ___TIGGO("Tiggo"),
	TAGAZ___VEGA("Vega"),
	TAGAZ___VORTEX_CORDA("Vortex Corda"),
	TAGAZ___VORTEX_ESTINA("Vortex Estina"),
	TAGAZ___VORTEX_TINGO("Vortex Tingo"),
	TAGAZ___S10("С10"),
	TAGAZ___S30("С30"),
	TAGAZ___DRUGAYA("Другая"),
	UAZ___2206("2206"),
	UAZ___3151("3151"),
	UAZ___31512("31512"),
	UAZ___31514("31514"),
	UAZ___31519("31519"),
	UAZ___3153("3153"),
	UAZ___3159("3159"),
	UAZ___3160("3160"),
	UAZ___452_BUHANKA("452 Буханка"),
	UAZ___469("469"),
	UAZ___HUNTER("Hunter"),
	UAZ___PATRIOT("Patriot"),
	UAZ___PICKUP("Pickup"),
	UAZ___SIMBIR("Симбир"),
	UAZ___DRUGAYA("Другая"),
	
	;
	
	private String readableName;
	
	private EModel(String str){
		readableName = str;
	}
	
	public String getReadableName(){
		return readableName;
	}
	
	
}
